// packages/opui/components/Form/Form.tsx
import { omit } from "solid-js"
import { dynamic } from "@solidjs/web"
import type { Props } from "./types.solid"

export default function Form(props: Props) {
  const rest = omit(props, "as", "children", "class")

  const Tag = dynamic(() => props.as || "form")

  return (
    <Tag class={["ui-form", props.class]} {...rest}>
      {props.children}
    </Tag>
  )
}

// packages/opui/components/Form/Form.svelte
<script lang="ts">
  import type { Props } from "./types.svelte"

  let {
    as: Tag = "form",
    children,
    class: className,
    ref = $bindable(null),
    ...rest
  }: Props = $props()
</script>

<svelte:element
  this={Tag}
  bind:this={ref}
  class={["ui-form", className]}
  {...rest}
>
  {@render children?.()}
</svelte:element>
