// packages/opui/components/Form/Form.vue
<script setup lang="ts">
import type { Props, Slots } from "./types.d.vue"

const props = withDefaults(defineProps<Props>(), {
  as: "form",
})
defineSlots<Slots>()
</script>

<template>
  <component :is="props.as" :class="['form', props.class]" v-bind="$attrs">
    <slot></slot>
  </component>
</template>

// packages/opui/components/Form/Form.svelte
<script lang="ts">
  import type { Props } from "./types.svelte"

  let {
    as: Tag = "form",
    children,
    class: className,
    ref = $bindable(null),
    ...rest
  }: Props = $props()
</script>

<svelte:element
  this={Tag}
  bind:this={ref}
  class={["ui-form", className]}
  {...rest}
>
  {@render children?.()}
</svelte:element>
