// src/component-examples/button-group/Size.svelte
<script lang="ts">
  import { Button, ButtonGroup } from "opui-css/svelte"
</script>

<ButtonGroup size="x-small" variant="outlined">
  <Button>x-small</Button>
  <Button>x-small</Button>
  <Button>x-small</Button>
</ButtonGroup>

<ButtonGroup size="small" variant="outlined">
  <Button>Small</Button>
  <Button>Small</Button>
  <Button>Small</Button>
</ButtonGroup>

<ButtonGroup variant="outlined">
  <Button>Default</Button>
  <Button>Default</Button>
  <Button>Default</Button>
</ButtonGroup>

<ButtonGroup size="large" variant="outlined">
  <Button>Large</Button>
  <Button>Large</Button>
  <Button>Large</Button>
</ButtonGroup>

// src/component-examples/button-group/Size.vue
<script setup lang="ts">
import { Button, ButtonGroup } from "opui-css/vue"
</script>

<template>
  <ButtonGroup size="x-small" variant="outlined">
    <Button>x-small</Button>
    <Button>x-small</Button>
    <Button>x-small</Button>
  </ButtonGroup>

  <ButtonGroup size="small" variant="outlined">
    <Button>Small</Button>
    <Button>Small</Button>
    <Button>Small</Button>
  </ButtonGroup>

  <ButtonGroup variant="outlined">
    <Button>Default</Button>
    <Button>Default</Button>
    <Button>Default</Button>
  </ButtonGroup>

  <ButtonGroup size="large" variant="outlined">
    <Button>Large</Button>
    <Button>Large</Button>
    <Button>Large</Button>
  </ButtonGroup>
</template>
