// src/component-examples/toast/Severity.vue
<script setup lang="ts">
import { Button } from "opui-css/vue"
</script>

<template>
<Button
  commandfor="toast-manager"
  command="--show-toast"
  data-title="Success!"
  data-severity="success"
  variant="filled"
  class="green"
>
  Success
</Button>
<Button
  commandfor="toast-manager"
  command="--show-toast"
  data-title="Something went wrong"
  data-severity="critical"
  variant="filled"
  class="red"
>
  Error
</Button>
<Button
  commandfor="toast-manager"
  command="--show-toast"
  data-title="Did you know?"
  data-severity="info"
  variant="filled"
  class="blue"
>
  Info
</Button>
</template>

// src/component-examples/toast/Severity.tsx
import { Toast } from "opui-css/solid"

export default function Example() {
  return (
    <>
      <Toast severity="info" title="Info" description="Informational message." />
      <Toast severity="warning" title="Warning" description="Warning message." />
      <Toast severity="critical" title="Error" description="Error message." />
      <Toast severity="success" title="Success" description="Success message." />
    </>
  )
}
