// src/component-examples/toggle/MultiSelect.svelte
<script lang="ts">
  import { ToggleButton, ToggleGroup } from "opui-css/svelte"
</script>

<ToggleGroup name="text-style">
  <ToggleButton value="bold" aria-label="Bold"><strong>B</strong></ToggleButton>
  <ToggleButton value="italic" aria-label="Italic"><i>I</i></ToggleButton>
  <ToggleButton value="underline" aria-label="Underline"><u>U</u></ToggleButton>
</ToggleGroup>

// src/component-examples/toggle/MultiSelect.vue
<script setup lang="ts">
import { ToggleButton, ToggleGroup } from "opui-css/vue"
</script>

<template>
<ToggleGroup name="text-style">
  <ToggleButton value="bold" aria-label="Bold"><strong>B</strong></ToggleButton>
  <ToggleButton value="italic" aria-label="Italic"><i>I</i></ToggleButton>
  <ToggleButton value="underline" aria-label="Underline"><u>U</u></ToggleButton>
</ToggleGroup>
</template>
