// packages/opui/components/Radio/Radio.tsx
import { createUniqueId, omit, Show } from "solid-js"
import RadioInput from "./RadioInput"
import type { RadioProps } from "./types.solid"

export default function Radio(props: RadioProps) {
  const rest = omit(
    props,
    "aria-describedby",
    "children",
    "class",
    "endText",
    "error",
    "hideLabel",
    "name",
    "size",
    "stack",
  )

  const id = createUniqueId()
  const endTextId = () => (props.endText ? id : undefined)
  const describedBy = () =>
    [endTextId(), props["aria-describedby"]].filter(Boolean).join(" ") ||
    undefined

  return (
    <label
      class={[
        "ui-radio",
        props.size && `ui-${props.size}`,
        {
          "ui-stack": props.stack,
        },
        props.class,
      ]}
      data-invalid={props.error ? "" : undefined}
    >
      <RadioInput
        {...rest}
        aria-describedby={describedBy()}
        aria-invalid={props.error ? "true" : undefined}
        name={props.name}
      />
      <Show when={props.children}>
        <span class={[props.hideLabel ? "ui-sr-only" : "ui-label"]}>
          {props.children}
        </span>
      </Show>
      <Show when={props.endText}>
        <span id={endTextId()} class="ui-end-text">
          {props.endText}
        </span>
      </Show>
    </label>
  )
}

// packages/opui/components/Radio/Radio.vue
<script setup lang="ts">
import RadioInput from "./RadioInput.vue"
import type { RadioProps, Slots } from "./types.d.vue"
import { useId } from "vue"

defineOptions({
  inheritAttrs: false,
})

const props = defineProps<RadioProps>()
defineSlots<Slots>()
const modelValue = defineModel<string | number | boolean | undefined>({
  default: undefined,
})

const endTextId = useId()
</script>

<template>
  <label
    :class="[
      'ui-radio',
      props.size && `ui-${props.size}`,
      {
        'ui-stack': props.stack,
      },
      props.class,
    ]"
    :data-invalid="props.error ? '' : undefined"
  >
    <RadioInput
      v-bind="$attrs"
      v-model="modelValue"
      :aria-describedby="
        [$slots['end-text'] ? endTextId : undefined, $attrs['aria-describedby']]
          .filter(Boolean)
          .join(' ') || undefined
      "
    />
    <span :class="[props.hideLabel ? 'ui-sr-only' : 'ui-label']"
      ><slot></slot
    ></span>
    <span :id="endTextId" class="ui-end-text" v-if="$slots['end-text']">
      <slot name="end-text"></slot>
    </span>
  </label>
</template>
