// packages/opui/components/Radio/RadioInput.svelte
<script lang="ts">
  import { getFieldContext } from "../FieldGroup/context"
  import type { RadioInputProps as Props } from "./types.svelte"

  let {
    checked,
    group = $bindable(),
    name,
    onchange,
    value,
    ...rest
  }: Props = $props()

  const field = getFieldContext()
</script>

<input
  type="radio"
  checked={(group === undefined ? checked : group === (value ?? true)) ||
    undefined}
  name={name ?? field?.name}
  onchange={(event) => {
    group = value ?? true
    onchange?.(event)
  }}
  {value}
  {...rest}
/>

// packages/opui/components/Radio/RadioInput.tsx
import { omit, useContext } from "solid-js"
import { FieldGroupContext } from "../FieldGroup/context"
import type { RadioInputProps } from "./types.solid"

export default function RadioInput(props: RadioInputProps) {
  const rest = omit(props, "name")
  const fieldGroup = useContext(FieldGroupContext)

  return <input type="radio" name={props.name ?? fieldGroup.name} {...rest} />
}
