// packages/opui/components/Radio/RadioInput.svelte
<script lang="ts">
  import { getFieldContext } from "../FieldGroup/context"
  import type { RadioInputProps as Props } from "./types.svelte"

  let {
    checked,
    group = $bindable(),
    name,
    onchange,
    value,
    ...rest
  }: Props = $props()

  const field = getFieldContext()
</script>

<input
  type="radio"
  checked={(group === undefined ? checked : group === (value ?? true)) ||
    undefined}
  name={name ?? field?.name}
  onchange={(event) => {
    group = value ?? true
    onchange?.(event)
  }}
  {value}
  {...rest}
/>

// packages/opui/components/Radio/RadioInput.vue
<script setup vapor lang="ts">
import { inject, useAttrs } from "vue"
import type { RadioInputProps } from "./types"
import { CurrentFieldNameKey } from "../FieldGroup/types.d.vue"

defineOptions({
  inheritAttrs: false,
})

defineProps<RadioInputProps>()
const modelValue = defineModel<string | number | boolean>()
const attrs = useAttrs()
const currentFieldName = inject(CurrentFieldNameKey, undefined)

if (
  modelValue.value === false &&
  attrs.checked !== undefined &&
  attrs.checked !== false
) {
  modelValue.value = (attrs.value as string | number | undefined) ?? "on"
}
</script>

<template>
  <input
    type="radio"
    :name="currentFieldName"
    v-bind="$attrs"
    v-model="modelValue"
  />
</template>
