// src/component-examples/list/EndCheckbox.tsx
import { CheckboxInput, List, ListItem } from "opui-css/solid"

export default function Example() {
  return (
    <List>
      <ListItem
        type="checkbox"
        for="checkbox-example-1"
        text={<div>Checkbox 1</div>}
        end={<CheckboxInput id="checkbox-example-1" />}
      />
      <ListItem
        type="checkbox"
        for="checkbox-example-2"
        text={<div>Checkbox 2</div>}
        end={<CheckboxInput id="checkbox-example-2" />}
      />
    </List>
  )
}

// src/component-examples/list/EndCheckbox.vue
<script setup lang="ts">
import { CheckboxInput, List, ListItem } from "opui-css/vue"
</script>

<template>
  <List>
    <ListItem type="checkbox" for="checkbox-example-1">
      <template #text><div>Checkbox 1</div></template>
      <template #end><CheckboxInput id="checkbox-example-1" /></template>
    </ListItem>
    <ListItem type="checkbox" for="checkbox-example-2">
      <template #text><div>Checkbox 2</div></template>
      <template #end><CheckboxInput id="checkbox-example-2" /></template>
    </ListItem>
  </List>
</template>
