// src/component-examples/list/EndKeyboard.svelte
<script lang="ts">
  import { List } from "@opui/svelte"
  import { ListItem } from "@opui/svelte"
</script>

<List>
  <ListItem headline="Save all">
    {#snippet end()}
      <div><kbd>CTRL+ALT+DEL</kbd></div>
    {/snippet}
  </ListItem>
  <ListItem headline="Save">
    {#snippet end()}
      <div><kbd>CTRL+S</kbd></div>
    {/snippet}
  </ListItem>
</List>

// src/component-examples/list/EndKeyboard.vue
<script setup lang="ts">
import { List, ListItem } from "opui-css/vue"
</script>

<template>
  <List>
    <ListItem headline="Save all">
      <template #end><kbd>CTRL+ALT+DEL</kbd></template>
    </ListItem>
    <ListItem headline="Save">
      <template #end><kbd>CTRL+S</kbd></template>
    </ListItem>
  </List>
</template>
