// src/component-examples/list/EndSwitch.vue
<script setup lang="ts">
import { List, ListItem, SwitchInput } from "opui-css/vue"
</script>

<template>
  <List>
    <ListItem type="switch" for="switch-example-1">
      <template #text>Switch 1</template>
      <template #end><SwitchInput id="switch-example-1" /></template>
    </ListItem>
    <ListItem type="switch" for="switch-example-2">
      <template #text>Switch 2</template>
      <template #end><SwitchInput id="switch-example-2" /></template>
    </ListItem>
  </List>
</template>

// src/component-examples/list/EndSwitch.svelte
<script lang="ts">
  import { List, ListItem, SwitchInput } from "opui-css/svelte"
</script>

<List>
  <ListItem type="switch" for="switch-example-1">
    {#snippet text()}Switch 1{/snippet}
    {#snippet end()}<SwitchInput id="switch-example-1" />{/snippet}
  </ListItem>
  <ListItem type="switch" for="switch-example-2">
    {#snippet text()}Switch 2{/snippet}
    {#snippet end()}<SwitchInput id="switch-example-2" />{/snippet}
  </ListItem>
</List>
