// src/component-examples/list/EndText.svelte
<script lang="ts">
  import { List, ListItem } from "opui-css/svelte"
</script>

<List>
  <ListItem headline="Headline">
    {#snippet end()}30kB{/snippet}
  </ListItem>
  <ListItem headline="Headline" description="Supporting text">
    {#snippet end()}99%{/snippet}
  </ListItem>
  <ListItem
    headline="Headline"
    description="Supporting text that truly is quite long enough to fill up multiple lines."
  >
    {#snippet end()}100+{/snippet}
  </ListItem>
</List>

// src/component-examples/list/EndText.vue
<script setup lang="ts">
import { List, ListItem } from "opui-css/vue"
</script>

<template>
  <List>
    <ListItem headline="Headline">
      <template #end>30kB</template>
    </ListItem>
    <ListItem headline="Headline" description="Supporting text">
      <template #end>99%</template>
    </ListItem>
    <ListItem
      headline="Headline"
      description="Supporting text that truly is quite long enough to fill up multiple lines."
    >
      <template #end>100+</template>
    </ListItem>
  </List>
</template>
