// src/component-examples/list/Inset.vue
<script setup lang="ts">
import { List, ListItem } from "opui-css/vue"
</script>

<template>
  <List>
    <ListItem headline="No inset">
      <template #start
        ><svg
          xmlns="http://www.w3.org/2000/svg"
          width="32"
          height="32"
          viewBox="0 0 32 32"
        >
          <path
            fill="currentColor"
            d="M16 16a7 7 0 1 0 0-14a7 7 0 0 0 0 14m-8.5 2A3.5 3.5 0 0 0 4 21.5v.5c0 2.393 1.523 4.417 3.685 5.793C9.859 29.177 12.802 30 16 30s6.14-.823 8.315-2.207C26.477 26.417 28 24.393 28 22v-.5a3.5 3.5 0 0 0-3.5-3.5z"
          ></path></svg
      ></template>
    </ListItem>
    <ListItem inset headline="Inset class">
      <p>Makes the text line up nicely</p>
    </ListItem>
    <ListItem inset headline="Inset class">
      <template #start><div>Hidden</div></template>
      <p>Any <code>div.start</code> will be hidden when inset</p>
    </ListItem>
  </List>
</template>

// src/component-examples/list/Inset.tsx
import { List, ListItem } from "opui-css/solid"

export default function Example() {
  return (
    <List>
      <ListItem
        headline="No inset"
        start={
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="32"
            height="32"
            viewBox="0 0 32 32"
          >
            <path
              fill="currentColor"
              d="M16 16a7 7 0 1 0 0-14a7 7 0 0 0 0 14m-8.5 2A3.5 3.5 0 0 0 4 21.5v.5c0 2.393 1.523 4.417 3.685 5.793C9.859 29.177 12.802 30 16 30s6.14-.823 8.315-2.207C26.477 26.417 28 24.393 28 22v-.5a3.5 3.5 0 0 0-3.5-3.5z"
            ></path>
          </svg>
        }
      />
      <ListItem inset headline="Inset class">
        <p>Makes the text line up nicely</p>
      </ListItem>
      <ListItem inset headline="Inset class" start="Hidden">
        <p>
          Any <code>div.ui-start</code> will be hidden when inset
        </p>
      </ListItem>
    </List>
  )
}
