// packages/opui/components/Drawer/Drawer.tsx
import { createUniqueId, merge, omit, Show } from "solid-js"
import type { Props } from "./types.solid"

export default function Drawer(rawProps: Props) {
  const props = merge(
    {
      backdrop: "blurred",
      closedby: "any",
      scrollLock: true,
      side: "inline-start",
    } as const,
    rawProps,
  )
  const rest = omit(
    props,
    "backdrop",
    "children",
    "class",
    "closedby",
    "content",
    "footer",
    "header",
    "id",
    "scrollLock",
    "side",
  )

  const uid = createUniqueId()
  const drawerId = () => props.id || uid

  return (
    <dialog
      id={drawerId()}
      class={[
        "ui-drawer",
        props.side && `ui-${props.side}`,
        {
          "ui-backdrop-transparent": props.backdrop === "transparent",
          "ui-scroll-lock": !!props.scrollLock,
        },
        props.class,
      ]}
      closedby={props.closedby}
      {...rest}
    >
      <Show when={props.header}>{props.header}</Show>

      <Show when={props.content}>
        <div class="ui-content">{props.content}</div>
      </Show>

      {props.children}

      <Show when={props.footer}>{props.footer}</Show>
    </dialog>
  )
}

// packages/opui/components/Drawer/Drawer.svelte
<script lang="ts">
  import type { Props } from "./types.svelte"

  let {
    backdrop = "blurred",
    class: className,
    closedby = "any",
    id,
    ref = $bindable(null),
    scrollLock = true,
    side = "inline-start",

    // Snippets
    children,
    content,
    footer,
    header,
    ...rest
  }: Props = $props()

  const componentId = $props.id()
</script>

<dialog
  bind:this={ref}
  {closedby}
  class={[
    "ui-drawer",
    side && `ui-${side}`,
    {
      "ui-backdrop-transparent": backdrop === "transparent",
      "ui-scroll-lock": scrollLock,
    },
    className,
  ]}
  id={id || `drawer-${componentId}`}
  {...rest}
>
  {@render header?.()}
  {#if content}
    <div class="ui-content">
      {@render content()}
    </div>
  {/if}
  {@render children?.()}
  {@render footer?.()}
</dialog>
