// packages/opui/components/Drawer/Drawer.svelte
<script lang="ts">
  import type { Props } from "./types.svelte"

  let {
    backdrop = "blurred",
    class: className,
    closedby = "any",
    id,
    ref = $bindable(null),
    scrollLock = true,
    side = "inline-start",

    // Snippets
    children,
    content,
    footer,
    header,
    ...rest
  }: Props = $props()

  const componentId = $props.id()
</script>

<dialog
  bind:this={ref}
  {closedby}
  class={[
    "ui-drawer",
    side && `ui-${side}`,
    {
      "ui-backdrop-transparent": backdrop === "transparent",
      "ui-scroll-lock": scrollLock,
    },
    className,
  ]}
  id={id || `drawer-${componentId}`}
  {...rest}
>
  {@render header?.()}
  {#if content}
    <div class="ui-content">
      {@render content()}
    </div>
  {/if}
  {@render children?.()}
  {@render footer?.()}
</dialog>

// packages/opui/components/Drawer/Drawer.vue
<script setup lang="ts">
import { useId, useSlots } from 'vue'
import type { Props } from './types'

const {
  backdrop = 'blurred',
  closedby = 'any',
  id,
  scrollLock = true,
  side = 'inline-start',
} = defineProps<Props>()

defineOptions({
  inheritAttrs: false,
})

const slots = useSlots()
const drawerId = id || useId()
</script>

<template>
  <dialog
    :id="drawerId"
    :class="[
      'drawer',
      side,
      {
        'backdrop-transparent': backdrop === 'transparent',
        'scroll-lock': scrollLock,
      },
      $props.class,
    ]"
    :closedby="closedby"
    v-bind="$attrs"
  >
    <slot v-if="slots.header" name="header"></slot>

    <div class="content">
      <slot name="content"></slot>
    </div>

    <slot v-if="slots.footer" name="footer"></slot>
  </dialog>
</template>
