// packages/opui/components/FieldSet/FieldSet.vue
<script setup lang="ts">
import type { Props, Slots } from "./types.d.vue"

const props = withDefaults(defineProps<Props>(), {
  as: "fieldset",
})
defineSlots<Slots>()

defineOptions({
  inheritAttrs: false,
})
</script>

<template>
  <component
    :is="props.as"
    :class="['ui-fieldset', props.class]"
    :role="props.as === 'fieldset' ? undefined : 'group'"
    v-bind="$attrs"
  >
    <slot></slot>
  </component>
</template>

// packages/opui/components/FieldSet/FieldSet.svelte
<script lang="ts">
  import type { Props } from "./types.svelte"

  let {
    as: Tag = "fieldset",
    children,
    class: className,
    ...rest
  }: Props = $props()
</script>

<svelte:element
  this={Tag}
  class={["ui-fieldset", className]}
  role={Tag === "fieldset" ? undefined : "group"}
  {...rest}
>
  {@render children?.()}
</svelte:element>
