// packages/opui/components/Switch/SwitchInput.tsx
import { omit, useContext } from "solid-js"
import { FieldGroupContext } from "../FieldGroup/context"
import type { SwitchInputProps } from "./types.solid"

export default function SwitchInput(props: SwitchInputProps) {
  const rest = omit(props, "name")
  const fieldGroup = useContext(FieldGroupContext)

  return (
    <input
      type="checkbox"
      name={props.name ?? fieldGroup.name}
      role="switch"
      {...rest}
    />
  )
}

// packages/opui/components/Switch/SwitchInput.vue
<script setup lang="ts">
import { inject } from "vue"
import type { SwitchInputProps } from "./types"
import { CurrentFieldNameKey } from "../FieldGroup/types.d.vue"

defineOptions({
  inheritAttrs: false,
})

defineProps<SwitchInputProps>()
const modelValue = defineModel<boolean | (string | number)[]>()
const currentFieldName = inject(CurrentFieldNameKey, undefined)
</script>

<template>
  <input
    type="checkbox"
    role="switch"
    :name="currentFieldName"
    v-bind="$attrs"
    v-model="modelValue"
  />
</template>
