// packages/opui/components/Switch/SwitchInput.svelte
<script lang="ts">
  import { getFieldContext } from "../FieldGroup/context"
  import type { SwitchInputProps as Props } from "./types.svelte"

  let {
    checked = $bindable(),
    group = $bindable(),
    name,
    value,
    ...rest
  }: Props = $props()

  const field = getFieldContext()

  const getChecked = () => (group ? group.includes(value) : !!checked)
  const setChecked = (isChecked: boolean) => {
    if (group) {
      group = isChecked
        ? [...group, value]
        : group.filter((item: string | number) => item !== value)
    } else {
      checked = isChecked
    }
  }
</script>

<input
  type="checkbox"
  role="switch"
  bind:checked={getChecked, setChecked}
  name={name ?? field?.name}
  {value}
  {...rest}
/>

// packages/opui/components/Switch/SwitchInput.tsx
import { omit, useContext } from "solid-js"
import { FieldGroupContext } from "../FieldGroup/context"
import type { SwitchInputProps } from "./types.solid"

export default function SwitchInput(props: SwitchInputProps) {
  const rest = omit(props, "name")
  const fieldGroup = useContext(FieldGroupContext)

  return (
    <input
      type="checkbox"
      name={props.name ?? fieldGroup.name}
      role="switch"
      {...rest}
    />
  )
}
