// packages/opui/components/Range/Range.vue
<script setup lang="ts">
import type { RangeProps, Slots } from "./types.d.vue"
import { useId } from "vue"

defineOptions({
  inheritAttrs: false,
})

const props = defineProps<RangeProps>()
defineSlots<Slots>()
const modelValue = defineModel<number | string>()

const inputId = props.id || useId()
const labelId = useId()
const startTextId = useId()
const endTextId = useId()
</script>

<template>
  <label
    :class="[
      'ui-range',
      props.variant && `ui-${props.variant}`,
      { 'ui-spread': props.spread },
      props.class,
    ]"
  >
    <span v-if="props.label || $slots.default" class="ui-label" :id="labelId">
      <slot>{{ props.label }}</slot>
    </span>
    <output
      v-if="props.valueSuffix !== undefined || $slots.value"
      class="ui-value"
      :for="inputId"
      :data-suffix="props.valueSuffix"
    >
      <slot name="value">{{ modelValue ?? props.value }}</slot>
    </output>
    <span
      v-if="props.startText || $slots['start-text']"
      class="ui-start-text"
      :id="startTextId"
    >
      <slot name="start-text">{{ props.startText }}</slot>
    </span>

    <input
      :aria-describedby="
        [
          props.startText || $slots['start-text'] ? startTextId : undefined,
          props.endText || $slots['end-text'] ? endTextId : undefined,
        ]
          .filter(Boolean)
          .join(' ') || undefined
      "
      :aria-labelledby="labelId"
      :disabled="props.disabled"
      :id="inputId"
      :list="props.list"
      :max="props.max"
      :min="props.min"
      :name="props.name"
      :step="props.step"
      type="range"
      v-bind="$attrs"
      v-model="modelValue"
    />

    <datalist v-if="props.options || $slots.datalist" :id="props.list">
      <template
        v-for="option in props.options"
        :key="typeof option === 'object' ? option.value : option"
      >
        <option
          :value="typeof option === 'object' ? option.value : option"
          :label="typeof option === 'object' ? option.label : undefined"
        />
      </template>
      <slot name="datalist"></slot>
    </datalist>

    <span
      v-if="props.endText || $slots['end-text']"
      class="ui-end-text"
      :id="endTextId"
    >
      <slot name="end-text">{{ props.endText }}</slot>
    </span>
  </label>
</template>

// packages/opui/components/Range/Range.svelte
<script lang="ts">
  import type { RangeProps as Props } from "./types.svelte"
  import { onMount, type Snippet } from "svelte"

  let {
    class: className,
    disabled,
    id,
    label,
    list,
    max,
    min,
    name,
    options,
    ref = $bindable(null),
    spread,
    step,
    value = $bindable(),
    valueSuffix,
    variant,

    // Snippets
    children,
    datalist,
    endText,
    startText,
    valueText,
    ...rest
  }: Props = $props()

  let mounted = $state(false)
  onMount(() => {
    mounted = true
  })

  const componentId = $props.id()
  const inputId = $derived(id || `range-${componentId}`)
  const labelId = $derived(
    label || children ? `range-label-${componentId}` : undefined,
  )
  const startTextId = $derived(
    startText ? `range-start-${componentId}` : undefined,
  )
  const endTextId = $derived(endText ? `range-end-${componentId}` : undefined)
</script>

{#snippet snippetString(ss: Snippet | string | undefined)}
  {#if typeof ss === "string"}
    {ss}
  {:else}
    {@render ss?.()}
  {/if}
{/snippet}

<label
  bind:this={ref}
  class={["ui-range", variant && `ui-${variant}`, { "ui-spread": spread }, className]}
>
  {#if labelId}
    <span class="ui-label" id={labelId}>
      {label}{@render children?.()}
    </span>
  {/if}
  {#if valueSuffix !== undefined || valueText}
    <output class="ui-value" for={inputId} data-suffix={valueSuffix}>
      {#if mounted}
        {value}{valueSuffix}
      {:else if valueText}
        {@render valueText()}
      {:else}
        {value}
      {/if}
    </output>
  {/if}
  {#if startTextId}
    <span class="ui-start-text" id={startTextId}>
      {@render snippetString(startText)}
    </span>
  {/if}
  <input
    aria-describedby={[startTextId, endTextId].filter(Boolean).join(" ") ||
      undefined}
    aria-labelledby={labelId}
    bind:value
    {disabled}
    id={inputId}
    {list}
    {max}
    {min}
    {name}
    {step}
    type="range"
    {...rest}
  />
  {#if options || datalist}
    <datalist id={list}>
      {#each options ?? [] as option}
        {#if typeof option === "object"}
          <option value={option.value} label={option.label}></option>
        {:else}
          <option value={option}></option>
        {/if}
      {/each}
      {@render datalist?.()}
    </datalist>
  {/if}
  {#if endTextId}
    <span class="ui-end-text" id={endTextId}>
      {@render snippetString(endText)}
    </span>
  {/if}
</label>
