// packages/opui/components/Range/Range.tsx
import {
  createSignal,
  createUniqueId,
  For,
  omit,
  Show,
  useContext,
} from "solid-js"
import { FieldGroupContext } from "../FieldGroup/context"
import type { RangeProps } from "./types.solid"

export default function Range(props: RangeProps) {
  const fieldGroup = useContext(FieldGroupContext)
  const rest = omit(
    props,
    "children",
    "class",
    "datalist",
    "endText",
    "error",
    "id",
    "label",
    "list",
    "name",
    "options",
    "spread",
    "startText",
    "value",
    "valueSuffix",
    "valueText",
    "variant",
  )

  const uid = createUniqueId()
  const labelUid = createUniqueId()
  const startTextUid = createUniqueId()
  const endTextUid = createUniqueId()

  const [current, setCurrent] = createSignal(() => props.value)

  const hasLabel = () => !!(props.label || props.children)
  const hasStartText = () => !!props.startText
  const hasEndText = () => !!props.endText
  const hasValue = () =>
    props.valueSuffix !== undefined || props.valueText !== undefined

  const defaultValue = () => {
    const min = Number(props.min ?? 0)
    const max = Math.max(min, Number(props.max ?? 100))
    const step = props.step === "any" ? 0 : Number(props.step ?? 1)
    const middle = min + (max - min) / 2
    if (!step) return middle
    const value = min + Math.round((middle - min) / step) * step
    return value > max ? value - step : value
  }

  const inputId = () => props.id || (hasValue() ? uid : undefined)
  const labelId = () => (hasLabel() ? labelUid : undefined)
  const startTextId = () => (hasStartText() ? startTextUid : undefined)
  const endTextId = () => (hasEndText() ? endTextUid : undefined)

  const describedBy = () =>
    [startTextId(), endTextId()].filter(Boolean).join(" ") || undefined

  return (
    <label
      class={[
        "ui-range",
        props.variant && `ui-${props.variant}`,
        { "ui-spread": props.spread },
        props.class,
      ]}
      data-invalid={props.error ? "" : undefined}
      onInput={(event) => {
        if (event.target instanceof HTMLInputElement) {
          setCurrent(event.target.value)
        }
      }}
    >
      <Show when={hasLabel()}>
        <span class="ui-label" id={labelId()}>
          {props.label}
          {props.children}
        </span>
      </Show>
      <Show when={hasValue()}>
        <output
          class="ui-value"
          data-suffix={props.valueSuffix}
          for={inputId()}
        >
          {props.valueText ??
            `${current() ?? defaultValue()}${props.valueSuffix ?? ""}`}
        </output>
      </Show>
      <Show when={hasStartText()}>
        <span class="ui-start-text" id={startTextId()}>
          {props.startText}
        </span>
      </Show>
      <input
        aria-describedby={describedBy()}
        aria-invalid={props.error ? "true" : undefined}
        aria-labelledby={labelId()}
        id={inputId()}
        list={props.list}
        name={props.name ?? fieldGroup.name}
        type="range"
        value={props.value}
        {...rest}
      />
      <Show when={props.options || props.datalist}>
        <datalist id={props.list}>
          <For each={props.options}>
            {(option) =>
              typeof option === "object" ? (
                <option value={option.value} label={option.label} />
              ) : (
                <option value={option} />
              )
            }
          </For>
          {props.datalist}
        </datalist>
      </Show>
      <Show when={hasEndText()}>
        <span class="ui-end-text" id={endTextId()}>
          {props.endText}
        </span>
      </Show>
    </label>
  )
}

// packages/opui/components/Range/Range.svelte
<script lang="ts">
  import { getFieldContext } from "../FieldGroup/context"
  import type { RangeProps as Props } from "./types.svelte"

  let {
    class: className,
    endText,
    error,
    id,
    label,
    list,
    max,
    min,
    name,
    options,
    spread,
    startText,
    step,
    value = $bindable(),
    valueSuffix,
    variant,

    // Snippets
    children,
    datalist,
    valueText,
    ...rest
  }: Props = $props()

  const uid = $props.id()
  const field = getFieldContext()

  const hasLabel = $derived(!!label || !!children)
  const hasValue = $derived(valueSuffix !== undefined || !!valueText)
  const defaultValue = $derived.by(() => {
    const minValue = Number(min ?? 0)
    const maxValue = Math.max(minValue, Number(max ?? 100))
    const stepValue = step === "any" ? 0 : Number(step ?? 1)
    const middle = minValue + (maxValue - minValue) / 2
    if (!stepValue) return middle
    const stepped =
      minValue + Math.round((middle - minValue) / stepValue) * stepValue
    return stepped > maxValue ? stepped - stepValue : stepped
  })

  const inputId = $derived(id || (hasValue ? `range-${uid}` : undefined))
  const labelId = $derived(hasLabel ? `range-label-${uid}` : undefined)
  const startTextId = $derived(startText ? `range-start-${uid}` : undefined)
  const endTextId = $derived(endText ? `range-end-${uid}` : undefined)
  const describedBy = $derived(
    [startTextId, endTextId].filter(Boolean).join(" ") || undefined,
  )
</script>

<label
  class={[
    "ui-range",
    variant && `ui-${variant}`,
    { "ui-spread": spread },
    className,
  ]}
>
  {#if hasLabel}
    <span class="ui-label" id={labelId}>
      {label}
      {@render children?.()}
    </span>
  {/if}
  {#if hasValue}
    <output class="ui-value" for={inputId} data-suffix={valueSuffix}>
      {#if valueText}{@render valueText()}{:else}{value ??
          defaultValue}{valueSuffix ?? ""}{/if}
    </output>
  {/if}
  {#if startText}
    <span class="ui-start-text" id={startTextId}>
      {#if typeof startText === "string"}{startText}{:else}{@render startText()}{/if}
    </span>
  {/if}
  <input
    aria-describedby={describedBy}
    aria-invalid={error ? "true" : undefined}
    aria-labelledby={labelId}
    id={inputId}
    {list}
    {max}
    {min}
    name={name ?? field?.name}
    {step}
    type="range"
    bind:value
    {...rest}
  />
  {#if options || datalist}
    <datalist id={list}>
      {#each options ?? [] as option (typeof option === "object" ? option.value : option)}
        {#if typeof option === "object"}
          <option value={option.value} label={option.label}></option>
        {:else}
          <option value={option}></option>
        {/if}
      {/each}
      {@render datalist?.()}
    </datalist>
  {/if}
  {#if endText}
    <span class="ui-end-text" id={endTextId}>
      {#if typeof endText === "string"}{endText}{:else}{@render endText()}{/if}
    </span>
  {/if}
</label>
