// packages/opui/components/Anchor/Anchor.svelte
<script lang="ts">
  import type { Props } from "./types.svelte"

  let {
    alignment,
    class: className,
    id: idProp,
    ref = $bindable(null),
    trigger = "always",

    // Snippets
    anchored,
    children,
    ...rest
  }: Props = $props()

  const uid = $props.id()

  const insetMap: Record<string, string> = {
    "start start": "auto 100% 100% auto",
    "start end": "auto auto 100% 100%",
    "end start": "100% 100% auto auto",
    "end end": "100% auto auto 100%",
  }

  const isHover = $derived(trigger === "hover")
  const id = $derived(isHover ? (idProp ?? uid) : undefined)
</script>

<span
  bind:this={ref}
  class={["ui-anchor", className]}
  style:--anchor-position-area={alignment}
  style:--_anchor-inset={alignment ? insetMap[alignment] : undefined}
  {...rest}
>
  {#if isHover}
    <span {...{ interestfor: id }}>
      {@render children?.()}
    </span>
  {:else}
    {@render children?.()}
  {/if}
  <span class="ui-anchor-floating" {id} popover={isHover ? "hint" : undefined}>
    {@render anchored?.()}
  </span>
</span>

// packages/opui/components/Anchor/Anchor.vue
<script setup lang="ts">
import { useId } from 'vue'
import type { Props } from './types'

const {
  alignment,
  class: className,
  id: idProp,
  trigger = 'always',
} = defineProps<Props>()

const isHover = trigger === 'hover'
const uid = useId()
const id = isHover ? (idProp ?? uid) : undefined

const insetMap: Record<string, string> = {
  'start start': 'auto 100% 100% auto',
  'start end': 'auto auto 100% 100%',
  'end start': '100% 100% auto auto',
  'end end': '100% auto auto 100%',
}

const positionArea = alignment
  ? {
      '--anchor-position-area': alignment,
      '--_anchor-inset': insetMap[alignment],
    }
  : {}
</script>

<template>
  <span :class="['anchor', className]" :style="positionArea">
    <span v-if="isHover" :interestfor="id">
      <slot></slot>
    </span>
    <slot v-else></slot>
    <span class="anchor-floating" :id="id" :popover="isHover ? 'hint' : undefined">
      <slot name="anchored"></slot>
    </span>
  </span>
</template>
