// src/component-examples/select/Classic.tsx
import { ClassicSelect } from "opui-css/solid"

export default function Example() {
  return (
    <>
      <ClassicSelect label="Label">
        <option value="">-</option>
        <option>Option</option>
        <option>Option</option>
      </ClassicSelect>

      <ClassicSelect label="Label" variant="filled">
        <option value="">-</option>
        <option>Option 1</option>
        <option>Option 2</option>
      </ClassicSelect>
    </>
  )
}

// src/component-examples/select/Classic.svelte
<script lang="ts">
  import { ClassicSelect } from "opui-css/svelte"
</script>

<ClassicSelect label="Label">
  <option value="">-</option>
  <option>Option 1</option>
  <option>Option 2</option>
</ClassicSelect>

<ClassicSelect label="Label" variant="filled">
  <option value="">-</option>
  <option>Option 1</option>
  <option>Option 2</option>
</ClassicSelect>
