// src/component-examples/select/Orientation.vue
<script setup lang="ts">
import { Select } from "opui-css/vue"
</script>

<template>
  <Select spread>
    <template #label>Country</template>
    <template #description>Select your country of residence</template>
    <option value="">Select a country</option>
    <option>Denmark</option>
    <option>Finland</option>
    <option>Iceland</option>
    <option>Norway</option>
    <option>Sweden</option>
  </Select>

  <Select spread variant="filled">
    <template #label>Language</template>
    <template #description>Choose your preferred language</template>
    <template #end-text>This affects UI translations</template>
    <option value="">Select a language</option>
    <option>Danish</option>
    <option>Finnish</option>
    <option>Icelandic</option>
    <option>Norwegian</option>
    <option>Swedish</option>
  </Select>

  <Select spread required>
    <template #label>Required</template>
    <template #description>You must select an option</template>
    <option value="">Select an option</option>
    <option>Option 1</option>
    <option>Option 2</option>
  </Select>

  <Select spread disabled>
    <template #label>Disabled</template>
    <template #description>This select is disabled</template>
    <option>Option 1</option>
  </Select>

  <Select spread error>
    <template #label>Invalid Select</template>
    <template #description>This select has an error</template>
    <template #end-text>Please select a valid option.</template>
    <option>Option 1</option>
  </Select>

  <Select spread>
    <template #label>Time zone</template>
    <template #description>Used for reminders and due dates</template>
    <template #prefix>UTC</template>
    <option>-03:00</option>
    <option>+00:00</option>
    <option>+01:00</option>
    <option>+05:30</option>
    <option>+09:00</option>
  </Select>

  <Select spread variant="filled">
    <template #label>Region</template>
    <template #description>Affects data residency and latency</template>
    <template #prefix>
      <svg
        width="16"
        height="16"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        <circle cx="12" cy="12" r="10"></circle>
        <path d="M2 12h20"></path>
        <path
          d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"
        ></path>
      </svg>
    </template>
    <template #end-text>Cannot be changed after deploy</template>
    <option value="">-</option>
    <option>eu-north-1</option>
    <option>us-east-1</option>
    <option>ap-southeast-1</option>
  </Select>
</template>

// src/component-examples/select/Orientation.svelte
<script lang="ts">
  import { Select } from "opui-css/svelte"
</script>

<Select spread>
  {#snippet label()}Country{/snippet}
  {#snippet description()}Select your country of residence{/snippet}
  <option value="">Select a country</option>
  <option>Denmark</option>
  <option>Finland</option>
  <option>Iceland</option>
  <option>Norway</option>
  <option>Sweden</option>
</Select>

<Select spread variant="filled">
  {#snippet label()}Language{/snippet}
  {#snippet description()}Choose your preferred language{/snippet}
  {#snippet endText()}This affects UI translations{/snippet}
  <option value="">Select a language</option>
  <option>Danish</option>
  <option>Finnish</option>
  <option>Icelandic</option>
  <option>Norwegian</option>
  <option>Swedish</option>
</Select>

<Select spread required>
  {#snippet label()}Required{/snippet}
  {#snippet description()}You must select an option{/snippet}
  <option value="">Select an option</option>
  <option>Option 1</option>
  <option>Option 2</option>
</Select>

<Select spread disabled>
  {#snippet label()}Disabled{/snippet}
  {#snippet description()}This select is disabled{/snippet}
  <option>Option 1</option>
</Select>

<Select spread error>
  {#snippet label()}Invalid Select{/snippet}
  {#snippet description()}This select has an error{/snippet}
  {#snippet endText()}Please select a valid option.{/snippet}
  <option>Option 1</option>
</Select>

<Select spread>
  {#snippet label()}Time zone{/snippet}
  {#snippet description()}Used for reminders and due dates{/snippet}
  {#snippet prefix()}UTC{/snippet}
  <option>-03:00</option>
  <option>+00:00</option>
  <option>+01:00</option>
  <option>+05:30</option>
  <option>+09:00</option>
</Select>

<Select spread variant="filled">
  {#snippet label()}Region{/snippet}
  {#snippet description()}Affects data residency and latency{/snippet}
  {#snippet prefix()}
    <svg
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
      <circle cx="12" cy="12" r="10"></circle>
      <path d="M2 12h20"></path>
      <path
        d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"
      ></path>
    </svg>
  {/snippet}
  {#snippet endText()}Cannot be changed after deploy{/snippet}
  <option value="">-</option>
  <option>eu-north-1</option>
  <option>us-east-1</option>
  <option>ap-southeast-1</option>
</Select>
