// packages/opui/components/List/List.vue
<script setup lang="ts">
import type { Props } from './types'

const {
  bordered,
  dense,
  gutterless,
  variant,
} = defineProps<Props>()

defineOptions({
  inheritAttrs: false,
})
</script>

<template>
  <ul
    :class="[
      'list',
      {
        bordered,
        dense,
        gutterless,
      },
      variant,
      $props.class,
    ]"
    v-bind="$attrs"
  >
    <slot></slot>
  </ul>
</template>

// packages/opui/components/List/List.svelte
<script lang="ts">
  import type { Props } from "./types.svelte"

  let {
    bordered,
    class: className,
    dense,
    gutterless,
    ref = $bindable(null),
    variant,

    // Snippets
    children,
    ...rest
  }: Props = $props()
</script>

<ul
  bind:this={ref}
  class={[
    "ui-list",
    {
      "ui-bordered": bordered,
      "ui-dense": dense,
      "ui-gutterless": gutterless,
    },
    variant && `ui-${variant}`,
    className,
  ]}
  {...rest}
>
  {@render children?.()}
</ul>
