// packages/opui/components/List/List.svelte
<script lang="ts">
  import type { Props } from "./types.svelte"

  let {
    bordered,
    class: className,
    dense,
    gutterless,
    variant,

    // Snippets
    children,
    ...rest
  }: Props = $props()
</script>

<ul
  class={[
    "ui-list",
    {
      "ui-bordered": bordered,
      "ui-dense": dense,
      "ui-gutterless": gutterless,
    },
    variant && `ui-${variant}`,
    className,
  ]}
  {...rest}
>
  {@render children?.()}
</ul>

// packages/opui/components/List/List.tsx
import { omit } from "solid-js"
import type { Props } from "./types.solid"

export default function List(props: Props) {
  const rest = omit(
    props,
    "bordered",
    "children",
    "class",
    "dense",
    "gutterless",
    "variant",
  )

  return (
    <ul
      class={[
        "ui-list",
        {
          "ui-bordered": props.bordered,
          "ui-dense": props.dense,
          "ui-gutterless": props.gutterless,
        },
        props.variant && `ui-${props.variant}`,
        props.class,
      ]}
      {...rest}
    >
      {props.children}
    </ul>
  )
}
