// packages/opui/components/Dialog/Dialog.svelte
<script lang="ts">
  import type { Props } from "./types.svelte"

  let {
    actions,
    actionsAlign,
    children,
    class: className,
    closedby,
    content,
    header,
    ref = $bindable(null),
    ...rest
  }: Props = $props()
</script>

<dialog
  bind:this={ref}
  class={["ui-dialog ui-card ui-elevated", className]}
  {closedby}
  {...rest}
>
  {#if header}
    <hgroup>
      {#if typeof header === "string"}
        {header}
      {:else}
        {@render header()}
      {/if}
    </hgroup>
  {/if}
  {#if content}
    <div class="ui-content">
      {@render content()}
    </div>
  {/if}
  {@render children?.()}
  {#if actions}
    <div class={["ui-actions", actionsAlign && `ui-align-${actionsAlign}`]}>
      {@render actions()}
    </div>
  {/if}
</dialog>

// packages/opui/components/Dialog/Dialog.tsx
import { omit, Show } from "solid-js"
import type { Props } from "./types.solid"

export default function Dialog(props: Props) {
  const rest = omit(
    props,
    "actions",
    "actionsAlign",
    "children",
    "class",
    "content",
    "header",
  )

  return (
    <dialog
      class={["ui-dialog", "ui-card", "ui-elevated", props.class]}
      {...rest}
    >
      <Show when={props.header}>
        <hgroup>{props.header}</hgroup>
      </Show>

      <Show when={props.content}>
        <div class="ui-content">{props.content}</div>
      </Show>

      {props.children}

      <Show when={props.actions}>
        <div
          class={[
            "ui-actions",
            props.actionsAlign && `ui-align-${props.actionsAlign}`,
          ]}
        >
          {props.actions}
        </div>
      </Show>
    </dialog>
  )
}
