// packages/opui/components/Dialog/Dialog.vue
<script setup lang="ts">
import type { Props, Slots } from "./types.d.vue"

const { actionsAlign, closedby } = defineProps<Props>()

defineOptions({
  inheritAttrs: false,
})

const slots = defineSlots<Slots>()
</script>

<template>
  <dialog
    :class="['dialog', 'card', 'elevated', $props.class]"
    :closedby="closedby"
    v-bind="$attrs"
  >
    <hgroup v-if="slots.header">
      <slot name="header"></slot>
    </hgroup>

    <div v-if="slots.content" class="content">
      <slot name="content"></slot>
    </div>

    <slot></slot>

    <div
      v-if="slots.actions"
      :class="['actions', actionsAlign && `align-${actionsAlign}`]"
    >
      <slot name="actions"></slot>
    </div>
  </dialog>
</template>

// packages/opui/components/Dialog/Dialog.svelte
<script lang="ts">
  import type { Props } from "./types.svelte"

  let {
    actions,
    actionsAlign,
    children,
    class: className,
    closedby,
    content,
    header,
    ref = $bindable(null),
    ...rest
  }: Props = $props()
</script>

<dialog
  bind:this={ref}
  class={["ui-dialog ui-card ui-elevated", className]}
  {closedby}
  {...rest}
>
  {#if header}
    <hgroup>
      {#if typeof header === "string"}
        {header}
      {:else}
        {@render header()}
      {/if}
    </hgroup>
  {/if}
  {#if content}
    <div class="ui-content">
      {@render content()}
    </div>
  {/if}
  {@render children?.()}
  {#if actions}
    <div class={["ui-actions", actionsAlign && `ui-align-${actionsAlign}`]}>
      {@render actions()}
    </div>
  {/if}
</dialog>
