// src/component-examples/textarea/Headers.svelte
<script lang="ts">
  import { Textarea } from "opui-css/svelte"
</script>

<Textarea label="Code" placeholder="console.log('Hello, world!')">
  {#snippet header()}script.js{/snippet}
</Textarea>

<Textarea label="Comment" placeholder="Write a comment...">
  {#snippet footer()}0 / 280{/snippet}
</Textarea>

// src/component-examples/textarea/Headers.vue
<script setup lang="ts">
import { Textarea } from "opui-css/vue"
</script>

<template>
  <Textarea label="Code" placeholder="console.log('Hello, world!')">
    <template #header>script.js</template>
  </Textarea>

  <Textarea label="Comment" placeholder="Write a comment...">
    <template #footer>0 / 280</template>
  </Textarea>
</template>
