// src/component-examples/textarea/Headers.vue
<script setup lang="ts">
import { Textarea } from "opui-css/vue"
</script>

<template>
  <Textarea label="Code" placeholder="console.log('Hello, world!')">
    <template #header>script.js</template>
  </Textarea>

  <Textarea label="Comment" placeholder="Write a comment...">
    <template #footer>0 / 280</template>
  </Textarea>
</template>

// src/component-examples/textarea/Headers.tsx
import { Textarea } from "opui-css/solid"

export default function Example() {
  return (
    <>
      <Textarea
        label="Code"
        placeholder="console.log('Hello, world!')"
        header="script.js"
      />

      <Textarea
        label="Comment"
        placeholder="Write a comment..."
        footer="0 / 280"
      />
    </>
  )
}
