// packages/opui/components/Select/Select.tsx
import { createUniqueId, For, merge, omit, Show } from "solid-js"
import type { Props } from "./types.solid"

export default function Select(rawProps: Props) {
  const props = merge({ items: [], variant: "outlined" }, rawProps)
  const rest = omit(
    props,
    "children",
    "class",
    "dense",
    "description",
    "endText",
    "error",
    "footer",
    "header",
    "id",
    "items",
    "label",
    "prefix",
    "size",
    "spread",
    "suffix",
    "variant",
  )

  const uid = createUniqueId()
  const labelId = createUniqueId()
  const endTextId = createUniqueId()

  const selectId = () => props.id ?? uid

  return (
    <label
      class={[
        "ui-select",
        props.size && `ui-${props.size}`,
        {
          "ui-filled": props.variant === "filled",
          "ui-spread": !!props.spread,
        },
        props.class,
      ]}
      data-invalid={props.error || undefined}
    >
      <Show when={props.label}>
        <span class="ui-label" id={labelId}>
          {props.label}
        </span>
      </Show>
      <Show when={props.description}>
        <span class="ui-start-text">{props.description}</span>
      </Show>
      <span class="ui-field">
        <select
          aria-labelledby={props.label ? labelId : undefined}
          id={selectId()}
          {...rest}
        >
          <button>
            <selectedcontent></selectedcontent>
          </button>
          <div class={["ui-list", { "ui-dense": !!props.dense }]}>
            <For each={props.items}>
              {(item) => <option value={item.value}>{item.text}</option>}
            </For>
            {props.children}
          </div>
        </select>
        <Show when={props.prefix}>
          <span class="ui-prefix">{props.prefix}</span>
        </Show>
        <Show when={props.suffix}>
          <span class="ui-suffix">{props.suffix}</span>
        </Show>
        <Show when={props.header}>
          <span class="ui-header">{props.header}</span>
        </Show>
        <Show when={props.footer}>
          <span class="ui-footer">{props.footer}</span>
        </Show>
      </span>
      <Show when={props.endText}>
        <span id={endTextId} class="ui-end-text">
          {props.endText}
        </span>
      </Show>
    </label>
  )
}

// packages/opui/components/Select/Select.vue
<script setup vapor lang="ts">
import { useId } from "vue"
import type { Props, Slots } from "./types.d.vue"

defineOptions({
  inheritAttrs: false,
})

const props = withDefaults(defineProps<Props>(), {
  items: () => [],
  variant: "outlined",
})
defineSlots<Slots>()
const modelValue = defineModel<string | number | (string | number)[]>()

const selectId = props.id || useId()
const labelId = useId()
const endTextId = useId()
</script>

<template>
  <label
    :class="[
      'ui-select',
      props.size && `ui-${props.size}`,
      {
        'ui-filled': props.variant === 'filled',
        'ui-spread': props.spread,
      },
      props.class,
    ]"
    :data-invalid="props.error || undefined"
  >
    <span v-if="props.label || $slots.label" class="ui-label" :id="labelId">
      <slot name="label">{{ props.label }}</slot>
    </span>

    <span v-if="props.description || $slots.description" class="ui-start-text">
      <slot name="description">{{ props.description }}</slot>
    </span>

    <span class="ui-field">
      <select
        :aria-labelledby="props.label ? labelId : undefined"
        :id="selectId"
        v-bind="$attrs"
        v-model="modelValue"
      >
        <button v-pre>
          <selectedcontent></selectedcontent>
        </button>
        <div :class="['ui-list', { 'ui-dense': props.dense }]">
          <option
            v-for="item in props.items"
            :key="item.value"
            :value="item.value"
          >
            {{ item.text }}
          </option>
          <slot></slot>
        </div>
      </select>
      <span class="ui-prefix" v-if="$slots.prefix"
        ><slot name="prefix"></slot
      ></span>
      <span class="ui-suffix" v-if="$slots.suffix"
        ><slot name="suffix"></slot
      ></span>
      <span class="ui-header" v-if="$slots.header"
        ><slot name="header"></slot
      ></span>
      <span class="ui-footer" v-if="$slots.footer"
        ><slot name="footer"></slot
      ></span>
    </span>

    <span
      v-if="props.endText || $slots['end-text']"
      :id="endTextId"
      class="ui-end-text"
    >
      <slot name="end-text">{{ props.endText }}</slot>
    </span>
  </label>
</template>
