// packages/opui/components/Rating/Rating.vue
<script setup lang="ts">
import type { Props } from "./types.d.vue"
import { computed } from "vue"

const {
  clearLabel = "No rating",
  disabled,
  error,
  label,
  max = 5,
  name,
  required,
  size,
  starLabel = (value: number) => (value === 1 ? "1 star" : `${value} stars`),
  value,
} = defineProps<Props>()
const modelValue = defineModel<number | string>()

const count = computed(() => Number(max))
const stars = computed(() =>
  Array.from({ length: count.value }, (_, index) => index + 1),
)
const current = computed(() => Number(modelValue.value ?? value))
const select = (star: number) => {
  modelValue.value = star
}
</script>

<template>
  <fieldset
    v-if="name"
    :class="['ui-rating', size && `ui-${size}`, $props.class]"
    :disabled="disabled"
  >
    <legend v-if="label">{{ label }}</legend>
    <input
      v-if="!required"
      :aria-invalid="error ? 'true' : undefined"
      :aria-label="clearLabel"
      :checked="current === 0"
      :name="name"
      type="radio"
      value="0"
      @change="select(0)"
    />
    <input
      v-for="star in stars"
      :key="star"
      :aria-invalid="error ? 'true' : undefined"
      :aria-label="starLabel(star)"
      :checked="current === star"
      :name="name"
      :required="required"
      type="radio"
      :value="star"
      @change="select(star)"
    />
  </fieldset>
  <meter
    v-else
    :aria-label="label"
    :class="['ui-rating', size && `ui-${size}`, $props.class]"
    :max="max"
    :style="count === 5 ? undefined : { '--_max': count }"
    :value="modelValue ?? value"
  ></meter>
</template>

// packages/opui/components/Rating/Rating.svelte
<script lang="ts">
  import type { Props } from "./types.svelte"

  let {
    class: className,
    clearLabel = "No rating",
    disabled,
    error,
    label,
    max = 5,
    name,
    required,
    size,
    starLabel = (value: number) => (value === 1 ? "1 star" : `${value} stars`),
    style,
    value = $bindable(),
    ...rest
  }: Props = $props()

  const count = $derived(Number(max))
  const stars = $derived(Array.from({ length: count }, (_, index) => index + 1))
  const current = $derived(Number(value))
  const invalid = $derived(error ? { "aria-invalid": "true" as const } : {})
</script>

{#if name}
  <fieldset
    class={["ui-rating", size && `ui-${size}`, className]}
    {disabled}
    {style}
    {...rest}
  >
    {#if label}
      <legend>{label}</legend>
    {/if}
    {#if !required}
      <input
        aria-label={clearLabel}
        checked={current === 0}
        {name}
        onchange={() => (value = 0)}
        type="radio"
        value="0"
        {...invalid}
      />
    {/if}
    {#each stars as star (star)}
      <input
        aria-label={starLabel(star)}
        checked={current === star}
        {name}
        onchange={() => (value = star)}
        {required}
        type="radio"
        value={star}
        {...invalid}
      />
    {/each}
  </fieldset>
{:else}
  <meter
    aria-label={label}
    class={["ui-rating", size && `ui-${size}`, className]}
    {max}
    style={[count === 5 ? undefined : `--_max: ${count};`, style]
      .filter(Boolean)
      .join(" ") || undefined}
    {value}
    {...rest}
  ></meter>
{/if}
