// packages/opui/components/Tabs/Tabs.svelte
<script lang="ts">
  import type { Props } from "./types.svelte"
  import { setTabsContext } from "./context"

  let {
    children,
    class: className,
    name,
    ref = $bindable(null),
    ...rest
  }: Props = $props()

  const id = $props.id()
  const groupName = $derived(name || `tabs-${id}`)

  setTabsContext({
    get groupName() {
      return groupName
    },
  })
</script>

<div bind:this={ref} class={["ui-tabs", className]} role="tablist" {...rest}>
  {@render children?.()}
</div>

// packages/opui/components/Tabs/Tabs.vue
<script setup lang="ts">
import { provide, useId } from 'vue'
import { TabsGroupNameKey, type Props } from './types'

const { class: className, name } = defineProps<Props>()

defineOptions({
  inheritAttrs: false,
})

const groupName = name || useId()
provide(TabsGroupNameKey, groupName)
</script>

<template>
  <div :class="['tabs', className]" role="tablist" v-bind="$attrs">
    <slot></slot>
  </div>
</template>
