// packages/opui/components/Tabs/TabsTab.svelte
<script lang="ts">
  import type { TabsTabProps as Props } from "./types.svelte"
  import { getTabsContext } from "./context"

  let {
    children,
    class: className,
    ref = $bindable(null),
    tabId,
    ...rest
  }: Props = $props()

  const context = getTabsContext()
</script>

<label
  bind:this={ref}
  for={tabId || context?.tabId}
  class={["ui-tab-label", className]}
  role="tab"
  {...rest}
>
  {@render children?.()}
</label>

// packages/opui/components/Tabs/TabsTab.tsx
import { omit, useContext } from "solid-js"
import { CurrentTabIdContext } from "./context"
import type { TabsTabProps } from "./types.solid"

export default function TabsTab(props: TabsTabProps) {
  const rest = omit(props, "children", "class", "tabId")

  const currentTabId = useContext(CurrentTabIdContext)

  return (
    <label
      for={props.tabId || currentTabId()}
      class={["ui-tab-label", props.class]}
      role="tab"
      {...rest}
    >
      {props.children}
    </label>
  )
}
