// packages/opui/components/Tabs/Tabs.tsx
import { createUniqueId, omit } from "solid-js"
import { TabsGroupNameContext } from "./context"
import type { Props } from "./types.solid"

export default function Tabs(props: Props) {
  const rest = omit(props, "children", "class", "name", "scrollable", "variant")

  const uid = createUniqueId()
  const groupName = () => props.name || uid

  return (
    <TabsGroupNameContext value={groupName}>
      <div
        class={[
          "ui-tabs",
          { "ui-scrollable": props.scrollable },
          props.variant && `ui-${props.variant}`,
          props.class,
        ]}
        {...rest}
      >
        {props.children}
      </div>
    </TabsGroupNameContext>
  )
}

// packages/opui/components/Tabs/Tabs.svelte
<script lang="ts">
  import { setTabsContext } from "./context"
  import type { Props } from "./types.svelte"

  let {
    children,
    class: className,
    name,
    scrollable,
    variant,
    ...rest
  }: Props = $props()

  const uid = $props.id()
  const groupName = $derived(name || `tabs-${uid}`)

  setTabsContext({
    get groupName() {
      return groupName
    },
  })
</script>

<div
  class={[
    "ui-tabs",
    { "ui-scrollable": scrollable },
    variant && `ui-${variant}`,
    className,
  ]}
  {...rest}
>
  {@render children?.()}
</div>
