// packages/opui/components/Tabs/TabsTab.svelte
<script lang="ts">
  import type { TabsTabProps as Props } from "./types.svelte"
  import { getTabsContext } from "./context"

  let {
    children,
    class: className,
    ref = $bindable(null),
    tabId,
    ...rest
  }: Props = $props()

  const context = getTabsContext()
</script>

<label
  bind:this={ref}
  for={tabId || context?.tabId}
  class={["ui-tab-label", className]}
  role="tab"
  {...rest}
>
  {@render children?.()}
</label>

// packages/opui/components/Tabs/TabsTab.vue
<script setup lang="ts">
import { inject } from 'vue'
import {
  CurrentTabIdKey,
  type TabsTabProps,
} from './types'

const { class: className, tabId } = defineProps<TabsTabProps>()

defineOptions({
  inheritAttrs: false,
})

const currentTabId = inject(CurrentTabIdKey, undefined)
</script>

<template>
  <label
    :for="tabId || currentTabId"
    :class="['tab-label', className]"
    role="tab"
    v-bind="$attrs"
  >
    <slot></slot>
  </label>
</template>
