// packages/opui/components/Tabs/TabsPanel.svelte
<script lang="ts">
  import type { TabsPanelProps as Props } from "./types.svelte"
  import { getTabsContext } from "./context"

  let {
    children,
    class: className,
    panelId,
    ref = $bindable(null),
    tabId,
    ...rest
  }: Props = $props()

  const context = getTabsContext()
</script>

<div
  bind:this={ref}
  id={panelId || context?.panelId}
  class={["ui-tab-panel", className]}
  role="tabpanel"
  aria-labelledby={tabId || context?.tabId}
  {...rest}
>
  {@render children?.()}
</div>

// packages/opui/components/Tabs/TabsPanel.tsx
import { omit, useContext } from "solid-js"
import { CurrentPanelIdContext, CurrentTabIdContext } from "./context"
import type { TabsPanelProps } from "./types.solid"

export default function TabsPanel(props: TabsPanelProps) {
  const rest = omit(props, "children", "class", "panelId", "tabId")

  const currentPanelId = useContext(CurrentPanelIdContext)
  const currentTabId = useContext(CurrentTabIdContext)

  return (
    <div
      id={props.panelId || currentPanelId()}
      class={["ui-tab-panel", props.class]}
      role="tabpanel"
      aria-labelledby={props.tabId || currentTabId()}
      {...rest}
    >
      {props.children}
    </div>
  )
}
