// packages/opui/components/Tabs/TabsItem.svelte
<script lang="ts">
  import type { TabsItemProps as Props } from "./types.svelte"
  import { getTabsContext, setTabsContext } from "./context"

  const id = $props.id()

  let {
    children,
    class: className,
    name,
    open,
    panelId = `panel-${id}`,
    ref = $bindable(null),
    tabId = `tab-${id}`,
    ...rest
  }: Props = $props()

  const parent = getTabsContext()
  const groupName = $derived(name || parent?.groupName)

  setTabsContext({
    get groupName() {
      return groupName
    },
    get panelId() {
      return panelId
    },
    get tabId() {
      return tabId
    },
  })
</script>

<input
  bind:this={ref}
  aria-controls={panelId}
  checked={open}
  class={["ui-tab-input", className]}
  id={tabId}
  name={groupName}
  type="radio"
  {...rest}
/>
{@render children?.()}

// packages/opui/components/Tabs/TabsItem.tsx
import { createUniqueId, omit, useContext } from "solid-js"
import {
  CurrentPanelIdContext,
  CurrentTabIdContext,
  TabsGroupNameContext,
} from "./context"
import type { TabsItemProps } from "./types.solid"

export default function TabsItem(props: TabsItemProps) {
  const rest = omit(
    props,
    "children",
    "class",
    "name",
    "open",
    "panelId",
    "tabId",
  )

  const parentGroupName = useContext(TabsGroupNameContext)
  const groupUid = createUniqueId()
  const panelUid = createUniqueId()
  const tabUid = createUniqueId()

  const groupName = () => props.name || parentGroupName() || groupUid
  const panelId = () => props.panelId || panelUid
  const tabId = () => props.tabId || tabUid

  return (
    <TabsGroupNameContext value={groupName}>
      <CurrentTabIdContext value={tabId}>
        <CurrentPanelIdContext value={panelId}>
          <input
            aria-controls={panelId()}
            checked={props.open}
            class={["ui-tab-input", props.class]}
            id={tabId()}
            name={groupName()}
            type="radio"
            {...rest}
          />
          {props.children}
        </CurrentPanelIdContext>
      </CurrentTabIdContext>
    </TabsGroupNameContext>
  )
}
