// packages/opui/components/ClassicSelect/ClassicSelect.svelte
<script lang="ts">
  import { getFieldContext } from "../FieldGroup/context"
  import type { ClassicSelectProps as Props } from "./types.svelte"

  let {
    class: className,
    endText,
    error,
    id,
    items = [],
    label,
    name,
    size,
    value = $bindable(),
    variant = "outlined",

    // Snippets
    children,
    ...rest
  }: Props = $props()

  const uid = $props.id()
  const field = getFieldContext()
  const selectId = $derived(id || `select-${uid}`)
  const endTextId = $derived(endText ? `end-text-${uid}` : undefined)
</script>

<label
  class={[
    "ui-select",
    size && `ui-${size}`,
    {
      "ui-filled": variant === "filled",
    },
    className,
  ]}
  data-invalid={error ? "" : undefined}
>
  {#if label}<span class="ui-label">{label}</span>{/if}
  <span class="ui-field">
    <select
      aria-describedby={endTextId}
      aria-invalid={error ? "true" : undefined}
      bind:value
      id={selectId}
      name={name ?? field?.name}
      {...rest}
    >
      {#each items as item (item.value)}
        <option value={item.value}>{item.text}</option>
      {/each}
      {@render children?.()}
    </select>
  </span>
  {#if endText}
    <span class="ui-end-text" id={endTextId}>{endText}</span>
  {/if}
</label>

// packages/opui/components/ClassicSelect/ClassicSelect.tsx
import { createUniqueId, For, merge, omit, Show, useContext } from "solid-js"
import { FieldGroupContext } from "../FieldGroup/context"
import type { ClassicSelectProps } from "./types.solid"

export default function ClassicSelect(rawProps: ClassicSelectProps) {
  const props = merge({ items: [], variant: "outlined" }, rawProps)
  const fieldGroup = useContext(FieldGroupContext)
  const rest = omit(
    props,
    "children",
    "class",
    "endText",
    "error",
    "id",
    "items",
    "label",
    "name",
    "size",
    "value",
    "variant",
  )

  const uid = createUniqueId()
  const endTextUid = createUniqueId()
  const selectId = () => props.id || uid
  const endTextId = () => (props.endText ? endTextUid : undefined)

  return (
    <label
      class={[
        "ui-select",
        props.size && `ui-${props.size}`,
        { "ui-filled": props.variant === "filled" },
        props.class,
      ]}
      data-invalid={props.error ? "" : undefined}
    >
      <Show when={props.label}>
        <span class="ui-label">{props.label}</span>
      </Show>
      <span class="ui-field">
        <select
          aria-describedby={endTextId()}
          aria-invalid={props.error ? "true" : undefined}
          id={selectId()}
          name={props.name ?? fieldGroup.name}
          {...rest}
        >
          <For each={props.items}>
            {(item) => (
              <option
                selected={item.value === props.value || undefined}
                value={item.value}
              >
                {item.text}
              </option>
            )}
          </For>
          {props.children}
        </select>
      </span>
      <Show when={props.endText}>
        <span class="ui-end-text" id={endTextId()}>
          {props.endText}
        </span>
      </Show>
    </label>
  )
}
