// packages/opui/components/ClassicSelect/ClassicSelect.svelte
<script lang="ts">
  import type { ClassicSelectProps as Props } from "./types.svelte"

  let {
    class: className,
    disabled,
    endText,
    error,
    id,
    items = [],
    label,
    name,
    ref = $bindable(null),
    required,
    size,
    value = $bindable(),
    variant = "outlined",

    // Snippets
    children,
    ...rest
  }: Props = $props()

  const componentId = $props.id()
  const labelId = `select-label-${componentId}`
</script>

<label
  bind:this={ref}
  class={[
    "ui-select",
    size && `ui-${size}`,
    {
      "ui-filled": variant === "filled",
    },
    className,
  ]}
  data-invalid={error || undefined}
>
  {#if label}
    <span class="ui-label" id={labelId}>
      {label}
    </span>
  {/if}
  <span class="ui-field">
    <select
      aria-labelledby={label ? labelId : undefined}
      bind:value
      {disabled}
      id={id || `select-${componentId}`}
      {name}
      {required}
      {...rest}
    >
      {#each items as item}
        <option value={item.value}>{item.text}</option>
      {/each}
      {@render children?.()}
    </select>
  </span>
  {#if endText}
    <span class="ui-end-text">{endText}</span>
  {/if}
</label>

// packages/opui/components/ClassicSelect/ClassicSelect.vue
<script setup lang="ts">
import type { ClassicSelectProps } from './types.ts'
import { useId } from 'vue'

defineOptions({
  inheritAttrs: false,
})

const props = withDefaults(defineProps<ClassicSelectProps>(), {
  items: () => [],
  variant: 'outlined',
})
const modelValue = defineModel<any>()

const selectId = props.id || useId()
const labelId = useId()
</script>

<template>
  <label
    :class="[
      'select',
      props.size,
      {
        filled: props.variant === 'filled',
      },
      props.class,
    ]"
    :data-invalid="props.critical || undefined"
  >
    <span v-if="props.label" class="label" :id="labelId">{{ props.label }}</span>
    <span class="field">
      <select
        :aria-labelledby="props.label ? labelId : undefined"
        :disabled="props.disabled"
        :id="selectId"
        :name="props.name"
        :required="props.required"
        v-bind="$attrs"
        v-model="modelValue"
      >
        <option v-for="item in props.items" :key="item.value" :value="item.value">
          {{ item.text }}
        </option>
        <slot></slot>
      </select>
    </span>
    <span v-if="props.endText" class="end-text">{{ props.endText }}</span>
  </label>
</template>
