// packages/opui/components/Button/Button.svelte
<script lang="ts">
  import type { Props } from "./types.svelte"

  let {
    as,
    class: className,
    color,
    disabled,
    href,
    iconOnly: _iconOnly,
    label,
    ripple,
    rounded,
    size,
    variant,

    // Snippets
    children,
    ...rest
  }: Props = $props()

  const Tag = $derived(as || (href ? "a" : "button"))
  const isButton = $derived(Tag === "button")
</script>

<svelte:element
  this={Tag}
  class={[
    "ui-button",
    {
      "ui-ripple": ripple,
      "ui-rounded": rounded,
    },
    size && `ui-${size}`,
    variant && `ui-${variant}`,
    color && `ui-${color}`,
    className,
  ]}
  aria-disabled={!isButton && disabled ? "true" : undefined}
  aria-label={label}
  disabled={isButton ? disabled : undefined}
  {href}
  type={isButton ? "button" : undefined}
  {...rest}
>
  {@render children?.()}
</svelte:element>

// packages/opui/components/Button/Button.tsx
import { omit } from "solid-js"
import { dynamic } from "@solidjs/web"
import type { Props } from "./types.solid"

export default function Button(props: Props) {
  const rest = omit(
    props,
    "as",
    "children",
    "class",
    "color",
    "disabled",
    "href",
    "iconOnly",
    "label",
    "ripple",
    "rounded",
    "size",
    "variant",
  )

  const tag = () => props.as || (props.href ? "a" : "button")
  const isButton = () => tag() === "button"
  const Tag = dynamic(tag)

  return (
    <Tag
      class={[
        "ui-button",
        {
          "ui-ripple": props.ripple,
          "ui-rounded": props.rounded,
        },
        props.size && `ui-${props.size}`,
        props.variant && `ui-${props.variant}`,
        props.color && `ui-${props.color}`,
        props.class,
      ]}
      aria-disabled={!isButton() && props.disabled ? "true" : undefined}
      aria-label={props.label}
      disabled={isButton() ? props.disabled : undefined}
      href={props.href}
      type={isButton() ? "button" : undefined}
      {...rest}
    >
      {props.children}
    </Tag>
  )
}
