// src/component-examples/switch/Spread.svelte
<script lang="ts">
  import { Switch } from "opui-css/svelte"
</script>

<Switch name="switch-spread" spread>
  Notifications
  {#snippet endText()}Receive alerts when someone mentions you.{/snippet}
</Switch>

<Switch name="switch-spread" spread required>
  Required
  {#snippet endText()}You must accept this to proceed.{/snippet}
</Switch>

<Switch name="switch-spread" spread disabled>
  Disabled
  {#snippet endText()}This switch is disabled.{/snippet}
</Switch>

<Switch name="switch-spread" spread error>
  Invalid Switch
  {#snippet endText()}There is an error with this switch.{/snippet}
</Switch>

// src/component-examples/switch/Spread.vue
<script setup lang="ts">
import { Switch } from "opui-css/vue"
</script>

<template>
  <Switch name="switch-spread" spread>
    Notifications
    <template #end-text>Receive alerts when someone mentions you.</template>
  </Switch>

  <Switch name="switch-spread" spread required>
    Required
    <template #end-text>You must accept this to proceed.</template>
  </Switch>

  <Switch name="switch-spread" spread disabled>
    Disabled
    <template #end-text>This switch is disabled.</template>
  </Switch>

  <Switch name="switch-spread" spread error>
    Invalid Switch
    <template #end-text>There is an error with this switch.</template>
  </Switch>
</template>
