// src/component-examples/switch/SupportingText.vue
<script setup lang="ts">
import { Switch } from "opui-css/vue"
</script>

<template>
  <Switch name="switch-supporting-text">
    Default
    <template #end-text>Supporting text</template>
  </Switch>
  <Switch name="switch-supporting-text" stack>
    Stack
    <template #end-text>Supporting text</template>
  </Switch>
</template>

// src/component-examples/switch/SupportingText.tsx
import { Switch } from "opui-css/solid"

export default function Example() {
  return (
    <>
      <Switch name="switch-supporting-text" endText="Supporting text">
        Default
      </Switch>
      <Switch name="switch-supporting-text" stack endText="Supporting text">
        Stack
      </Switch>
    </>
  )
}
