// packages/opui/components/ButtonGroup/ButtonGroup.svelte
<script lang="ts">
  import type { Props } from "./types.svelte"

  let {
    class: className,
    color,
    orientation,
    scrollable,
    shrink,
    size,
    variant,

    // Snippets
    children,
    ...rest
  }: Props = $props()
</script>

<div
  class={[
    "ui-button-group",
    color && `ui-${color}`,
    size && `ui-${size}`,
    variant && `ui-${variant}`,
    orientation && `ui-${orientation}`,
    { "ui-scrollable": scrollable, "ui-shrink": shrink },
    className,
  ]}
  role="group"
  {...rest}
>
  {@render children?.()}
</div>

// packages/opui/components/ButtonGroup/ButtonGroup.vue
<script setup lang="ts">
import type { Props, Slots } from "./types.d.vue"

const props = defineProps<Props>()
defineSlots<Slots>()
</script>

<template>
  <div
    :class="[
      'ui-button-group',
      props.color && `ui-${props.color}`,
      props.size && `ui-${props.size}`,
      props.variant && `ui-${props.variant}`,
      props.orientation && `ui-${props.orientation}`,
      { 'ui-scrollable': props.scrollable, 'ui-shrink': props.shrink },
      props.class,
    ]"
    role="group"
  >
    <slot></slot>
  </div>
</template>
