// packages/opui/components/ToggleButton/ToggleButton.svelte
<script lang="ts">
  import { getFieldContext } from "../FieldGroup/context"
  import { getToggleGroupContext } from "../ToggleGroup/context"
  import type { Props } from "./types.svelte"

  let {
    class: className,
    disabled,
    id,
    label,
    name,
    pressed,
    size,
    type,
    value,

    // Snippets
    children,
    ...rest
  }: Props = $props()

  const field = getFieldContext()
  const group = getToggleGroupContext()
  const uid = $props.id()

  const finalName = $derived(name || group?.groupName || field?.name)
  const finalType = $derived(
    group?.inputType === "radio"
      ? "radio"
      : type || group?.inputType || "checkbox",
  )
</script>

<label class={["ui-toggle-button", size && `ui-${size}`, className]}>
  <input
    checked={pressed}
    {disabled}
    id={id || `toggle-${uid}`}
    name={finalName}
    type={finalType}
    value={value || label}
    {...rest}
  />
  {#if children}{@render children()}{:else}{label}{/if}
</label>

// packages/opui/components/ToggleButton/ToggleButton.tsx
import { createUniqueId, omit, useContext } from "solid-js"
import { FieldGroupContext } from "../FieldGroup/context"
import { ToggleGroupContext } from "../ToggleGroup/context"
import type { Props } from "./types.solid"

export default function ToggleButton(props: Props) {
  const rest = omit(
    props,
    "children",
    "class",
    "disabled",
    "id",
    "label",
    "name",
    "pressed",
    "size",
    "type",
    "value",
  )

  const group = useContext(ToggleGroupContext)
  const field = useContext(FieldGroupContext)
  const uid = createUniqueId()
  const finalName = () => props.name || group.name || field.name
  const finalType = () =>
    group.type === "radio" ? "radio" : props.type || group.type || "checkbox"

  return (
    <label
      class={[
        "ui-toggle-button",
        { "ui-disabled": props.disabled },
        props.size && `ui-${props.size}`,
        props.class,
      ]}
    >
      <input
        checked={props.pressed}
        disabled={props.disabled}
        id={props.id || uid}
        name={finalName()}
        type={finalType()}
        value={props.value || props.label}
        {...rest}
      />
      {props.children ?? props.label}
    </label>
  )
}
