// src/component-examples/range/Surfaces.vue
<script setup lang="ts">
import { Range } from "opui-css/vue"
</script>

<template>
  <Range label="Default" />
  <Range variant="default">
    <code>default</code> = <code>var(--surface-default)</code>
  </Range>
  <Range variant="filled">
    <code>filled</code> = <code>var(--surface-filled)</code>
  </Range>
  <Range variant="tonal">
    <code>tonal</code> = <code>var(--surface-tonal)</code>
  </Range>
</template>

// src/component-examples/progress/Surfaces.tsx
import { Progress } from "opui-css/solid"

export default function Example() {
  return (
    <>
      <Progress value={50} max={100} label="Default" />
      <div style="background: var(--surface-2); padding: var(--size-3);">
        <Progress value={50} max={100} label="On surface" />
      </div>
    </>
  )
}
