// packages/opui/components/FieldDescription/FieldDescription.svelte
<script lang="ts">
  import type { Props } from "./types.svelte"

  export const title = "Field Description" as const

  const { children, class: className, ...rest }: Props = $props()

  let element = $state<HTMLParagraphElement | null>(null)
  export { element as this }
</script>

<p bind:this={element} class={["field-description", className]} {...rest}>
  {@render children?.()}
</p>

// packages/opui/components/FieldDescription/FieldDescription.vue
<script setup lang="ts">
import type { Props, Slots } from "./types.d.vue"

const props = defineProps<Props>()
defineSlots<Slots>()

defineOptions({
  inheritAttrs: false,
})
</script>

<template>
  <p :class="['ui-field-description', props.class]" v-bind="$attrs">
    <slot></slot>
  </p>
</template>
