// src/component-examples/checkbox/Indeterminate.svelte
<script lang="ts">
  import { Checkbox, FieldGroup, FieldLegend, FieldSet } from "opui-css/svelte"

  const items = ["Apples", "Bananas", "Cherries"]
  let checked = $state([true, false, false])

  const allChecked = $derived(checked.every(Boolean))
  const someChecked = $derived(checked.some(Boolean))
  const indeterminate = $derived(someChecked && !allChecked)

  function toggleAll() {
    const next = !allChecked
    checked = checked.map(() => next)
  }
</script>

<FieldSet class="indeterminate-demo">
  <FieldLegend>
    <Checkbox
      class="parent"
      bind:checked={() => allChecked, toggleAll}
      {indeterminate}>Select all</Checkbox
    >
  </FieldLegend>
  <FieldGroup name="indeterminate-children">
    {#each items as item, index (item)}
      <Checkbox class="child" bind:checked={checked[index]}>{item}</Checkbox>
    {/each}
  </FieldGroup>
</FieldSet>

// src/component-examples/checkbox/Indeterminate.vue
<script setup lang="ts">
import { computed, ref } from "vue"
import { Checkbox, FieldGroup, FieldLegend, FieldSet } from "opui-css/vue"

const items = ["Apples", "Bananas", "Cherries"]
const checked = ref([true, false, false])

const allChecked = computed(() => checked.value.every(Boolean))
const someChecked = computed(() => checked.value.some(Boolean))
const indeterminate = computed(() => someChecked.value && !allChecked.value)

function toggleAll() {
  const next = !allChecked.value
  checked.value = checked.value.map(() => next)
}
</script>

<template>
  <FieldSet class="indeterminate-demo">
    <FieldLegend>
      <Checkbox
        class="parent"
        :model-value="allChecked"
        :indeterminate="indeterminate"
        @update:model-value="toggleAll"
        >Select all</Checkbox
      >
    </FieldLegend>
    <FieldGroup name="indeterminate-children">
      <Checkbox
        class="child"
        v-for="(item, index) in items"
        :key="item"
        v-model="checked[index]"
        >{{ item }}</Checkbox
      >
    </FieldGroup>
  </FieldSet>
</template>
