// src/component-examples/checkbox/Spread.vue
<script setup lang="ts">
import { Checkbox } from "opui-css/vue"
</script>

<template>
  <Checkbox name="checkbox-spread" spread>
    Accept Terms & Conditions
    <template #end-text>I have read and agree to the privacy policy.</template>
  </Checkbox>

  <Checkbox name="checkbox-spread" spread required>
    Required
    <template #end-text>You must accept this to continue.</template>
  </Checkbox>

  <Checkbox name="checkbox-spread" spread disabled>
    Disabled
    <template #end-text>This checkbox is disabled.</template>
  </Checkbox>

  <Checkbox name="checkbox-spread" spread error>
    Invalid Checkbox
    <template #end-text>There is an error with this checkbox.</template>
  </Checkbox>
</template>

// src/component-examples/checkbox/Spread.svelte
<script lang="ts">
  import { Checkbox } from "opui-css/svelte"
</script>

<Checkbox name="checkbox-spread" spread>
  Accept Terms & Conditions
  {#snippet endText()}I have read and agree to the privacy policy.{/snippet}
</Checkbox>

<Checkbox name="checkbox-spread" spread required>
  Required
  {#snippet endText()}You must accept this to continue.{/snippet}
</Checkbox>

<Checkbox name="checkbox-spread" spread disabled>
  Disabled
  {#snippet endText()}This checkbox is disabled.{/snippet}
</Checkbox>

<Checkbox name="checkbox-spread" spread error>
  Invalid Checkbox
  {#snippet endText()}There is an error with this checkbox.{/snippet}
</Checkbox>
