// src/component-examples/checkbox/SupportingText.svelte
<script lang="ts">
  import { Checkbox } from "opui-css/svelte"
</script>

<Checkbox name="checkbox-supporting-text">
  Default
  {#snippet endText()}Supporting text{/snippet}
</Checkbox>
<Checkbox stack name="checkbox-supporting-text">
  Stack
  {#snippet endText()}Supporting text{/snippet}
</Checkbox>

// src/component-examples/checkbox/SupportingText.tsx
import { Checkbox } from "opui-css/solid"

export default function Example() {
  return (
    <>
      <Checkbox name="checkbox-supporting-text" endText="Supporting text">
        Default
      </Checkbox>
      <Checkbox stack name="checkbox-supporting-text" endText="Supporting text">
        Stack
      </Checkbox>
    </>
  )
}
