// src/component-examples/checkbox/SupportingText.svelte
<script lang="ts">
  import { Checkbox } from "opui-css/svelte"
</script>

<Checkbox name="checkbox-supporting-text">
  Default
  {#snippet endText()}Supporting text{/snippet}
</Checkbox>
<Checkbox stack name="checkbox-supporting-text">
  Stack
  {#snippet endText()}Supporting text{/snippet}
</Checkbox>

// src/component-examples/checkbox/SupportingText.vue
<script setup lang="ts">
import { Checkbox } from "opui-css/vue"
</script>

<template>
  <Checkbox name="checkbox-supporting-text">
    Default
    <template #end-text>Supporting text</template>
  </Checkbox>
  <Checkbox stack name="checkbox-supporting-text">
    Stack
    <template #end-text>Supporting text</template>
  </Checkbox>
</template>
