// packages/opui/components/FieldLegend/FieldLegend.vue
<script setup lang="ts">
import type { Props, Slots } from "./types.d.vue"

const props = withDefaults(defineProps<Props>(), {
  as: "legend",
})
defineSlots<Slots>()
</script>

<template>
  <component
    :is="props.as"
    :class="[{ legend: props.as !== 'legend' }, props.class]"
    v-bind="$attrs"
  >
    <slot></slot>
  </component>
</template>

// packages/opui/components/FieldLegend/FieldLegend.svelte
<script lang="ts">
  import type { Props } from "./types.svelte"

  let {
    as: Tag = "legend",
    children,
    class: className,
    ref = $bindable(null),
    ...rest
  }: Props = $props()
</script>

<svelte:element
  this={Tag}
  bind:this={ref}
  class={[{ "ui-legend": Tag !== "legend" }, className]}
  {...rest}
>
  {@render children?.()}
</svelte:element>
