// packages/opui/components/FieldLegend/FieldLegend.tsx
import { omit } from "solid-js"
import { dynamic } from "@solidjs/web"
import type { Props } from "./types.solid"

export default function FieldLegend(props: Props) {
  const rest = omit(props, "as", "children", "class")

  const tag = () => props.as || "legend"
  const Tag = dynamic(tag)

  return (
    <Tag class={[{ "ui-legend": tag() !== "legend" }, props.class]} {...rest}>
      {props.children}
    </Tag>
  )
}

// packages/opui/components/FieldLegend/FieldLegend.svelte
<script lang="ts">
  import type { Props } from "./types.svelte"

  let {
    as: Tag = "legend",
    children,
    class: className,
    ...rest
  }: Props = $props()
</script>

<svelte:element
  this={Tag}
  class={[{ "ui-legend": Tag !== "legend" }, className]}
  {...rest}
>
  {@render children?.()}
</svelte:element>
