// packages/opui/components/Textarea/Textarea.tsx
import { createUniqueId, omit, Show, useContext } from "solid-js"
import { FieldGroupContext } from "../FieldGroup/context"
import type { Props } from "./types.solid"

export default function Textarea(props: Props) {
  const fieldGroup = useContext(FieldGroupContext)
  const rest = omit(
    props,
    "aria-describedby",
    "autoFit",
    "children",
    "class",
    "description",
    "endText",
    "error",
    "footer",
    "header",
    "label",
    "name",
    "prefix",
    "size",
    "spread",
    "style",
    "suffix",
    "supportingText",
    "variant",
  )

  const uid = createUniqueId()
  const hasEndText = () => !!(props.endText || props.supportingText)
  const endTextId = () => (hasEndText() ? uid : undefined)
  const describedBy = () =>
    [endTextId(), props["aria-describedby"]].filter(Boolean).join(" ") ||
    undefined

  return (
    <label
      class={[
        "ui-textarea",
        props.size && `ui-${props.size}`,
        {
          "ui-auto-fit": props.autoFit,
          "ui-filled": props.variant === "filled",
          "ui-spread": props.spread,
        },
        props.class,
      ]}
      data-invalid={props.error ? "" : undefined}
      style={props.style}
    >
      <Show when={props.label}>
        <span class="ui-label">{props.label}</span>
      </Show>

      <Show when={props.description}>
        <span class="ui-start-text">{props.description}</span>
      </Show>

      <span class="ui-field">
        <textarea
          aria-describedby={describedBy()}
          aria-invalid={props.error ? "true" : undefined}
          name={props.name ?? fieldGroup.name}
          {...rest}
        ></textarea>
        <Show when={props.prefix}>
          <span class="ui-prefix">{props.prefix}</span>
        </Show>
        <Show when={props.suffix}>
          <span class="ui-suffix">{props.suffix}</span>
        </Show>
        <Show when={props.header}>
          <span class="ui-header">{props.header}</span>
        </Show>
        <Show when={props.footer}>
          <span class="ui-footer">{props.footer}</span>
        </Show>
      </span>

      <Show when={hasEndText()}>
        <span class="ui-end-text" id={endTextId()}>
          {props.endText}
          {props.supportingText}
        </span>
      </Show>

      {props.children}
    </label>
  )
}

// packages/opui/components/Textarea/Textarea.svelte
<script lang="ts">
  import { getFieldContext } from "../FieldGroup/context"
  import type { Props } from "./types.svelte"
  import type { Snippet } from "svelte"

  let {
    "aria-describedby": ariaDescribedBy,
    autoFit,
    class: className,
    error,
    id,
    name,
    size,
    spread,
    style,
    value = $bindable(),
    variant,

    // Snippets
    children,
    description,
    endText,
    footer,
    header,
    label,
    prefix,
    suffix,
    supportingText,
    ...rest
  }: Props = $props()

  const uid = $props.id()
  const field = getFieldContext()
  const endTextId = $derived(
    endText || supportingText ? `end-text-${uid}` : undefined,
  )
  const describedBy = $derived(
    [endTextId, ariaDescribedBy].filter(Boolean).join(" ") || undefined,
  )
</script>

{#snippet content(
  part: string | Snippet,
)}{#if typeof part === "string"}{part}{:else}{@render part()}{/if}{/snippet}

<label
  class={[
    "ui-textarea",
    size && `ui-${size}`,
    {
      "ui-auto-fit": autoFit,
      "ui-filled": variant === "filled",
      "ui-spread": spread,
    },
    className,
  ]}
  data-invalid={error ? "" : undefined}
  {style}
>
  {#if label}
    <span class="ui-label">{@render content(label)}</span>
  {/if}
  {#if description}
    <span class="ui-start-text">{@render content(description)}</span>
  {/if}
  <span class="ui-field">
    <textarea
      {...rest}
      aria-describedby={describedBy}
      aria-invalid={error ? "true" : undefined}
      bind:value
      {id}
      name={name ?? field?.name}
    ></textarea>
    {#if prefix}
      <span class="ui-prefix">{@render content(prefix)}</span>
    {/if}
    {#if suffix}
      <span class="ui-suffix">{@render content(suffix)}</span>
    {/if}
    {#if header}
      <span class="ui-header">{@render content(header)}</span>
    {/if}
    {#if footer}
      <span class="ui-footer">{@render content(footer)}</span>
    {/if}
  </span>
  {#if endText || supportingText}
    <span class="ui-end-text" id={endTextId}>
      {#if endText}{@render content(endText)}{/if}
      {#if supportingText}{@render content(supportingText)}{/if}
    </span>
  {/if}
  {@render children?.()}
</label>
