// packages/opui/components/Textarea/Textarea.tsx
import { createUniqueId, omit, Show } from "solid-js"
import type { Props } from "./types.solid"

export default function Textarea(props: Props) {
  const rest = omit(
    props,
    "autoFit",
    "children",
    "class",
    "description",
    "endText",
    "error",
    "filled",
    "footer",
    "header",
    "id",
    "label",
    "prefix",
    "small",
    "spread",
    "suffix",
    "supportingText",
  )

  const uid = createUniqueId()
  const fieldId = () => props.id || uid

  return (
    <label
      class={[
        "ui-textarea",
        {
          "ui-auto-fit": !!props.autoFit,
          "ui-filled": !!props.filled,
          "ui-spread": !!props.spread,
          "ui-small": !!props.small,
        },
        props.class,
      ]}
      data-invalid={props.error ? "true" : undefined}
    >
      <Show when={props.label}>
        <span class="ui-label">{props.label}</span>
      </Show>

      <Show when={props.description}>
        <span class="ui-start-text">{props.description}</span>
      </Show>

      <span class="ui-field">
        <textarea id={fieldId()} {...rest}></textarea>
        <Show when={props.prefix}>
          <span class="ui-prefix">{props.prefix}</span>
        </Show>
        <Show when={props.suffix}>
          <span class="ui-suffix">{props.suffix}</span>
        </Show>
        <Show when={props.header}>
          <span class="ui-header">{props.header}</span>
        </Show>
        <Show when={props.footer}>
          <span class="ui-footer">{props.footer}</span>
        </Show>
      </span>

      <Show when={props.endText || props.supportingText}>
        <span class="ui-end-text">
          {props.endText}
          {props.supportingText}
        </span>
      </Show>

      {props.children}
    </label>
  )
}

// packages/opui/components/Textarea/Textarea.vue
<script setup lang="ts">
import { useId } from "vue"
import type { Props, Slots } from "./types.d.vue"

defineOptions({
  inheritAttrs: false,
})

const props = defineProps<Props>()
defineSlots<Slots>()
const modelValue = defineModel<string>()

const fieldId = props.id || useId()
</script>

<template>
  <label
    :class="[
      'ui-textarea',
      {
        'ui-auto-fit': props.autoFit,
        'ui-filled': props.filled,
        'ui-spread': props.spread,
        'ui-small': props.small,
      },
      props.class,
    ]"
    :data-invalid="props.error || undefined"
  >
    <span v-if="props.label || $slots.label" class="ui-label">
      <slot name="label">{{ props.label }}</slot>
    </span>

    <span v-if="props.description || $slots.description" class="ui-start-text">
      <slot name="description">{{ props.description }}</slot>
    </span>

    <span class="ui-field">
      <textarea :id="fieldId" v-bind="$attrs" v-model="modelValue"></textarea>
      <span class="ui-prefix" v-if="$slots.prefix"
        ><slot name="prefix"></slot
      ></span>
      <span class="ui-suffix" v-if="$slots.suffix"
        ><slot name="suffix"></slot
      ></span>
      <span class="ui-header" v-if="$slots.header"
        ><slot name="header"></slot
      ></span>
      <span class="ui-footer" v-if="$slots.footer"
        ><slot name="footer"></slot
      ></span>
    </span>

    <span
      v-if="props.endText || $slots['end-text'] || $slots['supporting-text']"
      class="ui-end-text"
    >
      <slot name="end-text">{{ props.endText }}</slot
      ><slot name="supporting-text"></slot>
    </span>

    <slot></slot>
  </label>
</template>
