// packages/opui/components/ListItem/ListItem.svelte
<script lang="ts">
  import type { Props } from "./types.svelte"
  import type { Snippet } from "svelte"
  import type { HTMLAttributes } from "svelte/elements"

  let {
    as,
    borderTop,
    class: className,
    description,
    for: htmlFor,
    headline,
    href,
    inset,
    type,

    // Snippets
    children,
    end,
    start,
    submenu,
    text,
    ...rest
  }: Props = $props()

  const hasLabel = $derived(
    type === "checkbox" || type === "radio" || type === "switch",
  )
  const Tag = $derived(as ?? (href ? "a" : undefined))
</script>

{#snippet content(
  part: string | Snippet,
)}{#if typeof part === "string"}{part}{:else}{@render part()}{/if}{/snippet}

{#snippet startPart()}
  {#if start}
    <div class="ui-start">
      {@render content(start)}
    </div>
  {/if}
{/snippet}

{#snippet endPart()}
  {#if end}
    <div class="ui-end">
      {@render content(end)}
    </div>
  {/if}
{/snippet}

{#snippet body()}
  {@render startPart()}
  {#if headline || description || text}
    <div class="ui-text">
      {#if headline}<p>{headline}</p>{/if}
      {#if description}<p>{description}</p>{/if}
      {#if text}{@render content(text)}{/if}
      {@render children?.()}
    </div>
  {:else}
    {@render children?.()}
  {/if}
  {@render endPart()}
{/snippet}

<li
  class={[
    {
      "ui-border-top": borderTop,
      "ui-inset": inset,
    },
    className,
  ]}
  {...(Tag ? {} : rest) as HTMLAttributes<HTMLLIElement>}
>
  {#if hasLabel}
    <label class={type && `ui-${type}`} for={htmlFor}>
      {@render startPart()}
      {#if text || headline || description}
        <div class="ui-text">
          {#if headline}<p>{headline}</p>{/if}
          {#if description}<p>{description}</p>{/if}
          {#if text}{@render content(text)}{/if}
        </div>
      {/if}
      {@render endPart()}
      {@render children?.()}
    </label>
  {:else if Tag}
    <svelte:element this={Tag} {href} {...rest as HTMLAttributes<HTMLElement>}>
      {@render body()}
    </svelte:element>
  {:else}
    {@render body()}
  {/if}
  {#if submenu}{@render content(submenu)}{/if}
</li>

// packages/opui/components/ListItem/ListItem.tsx
import { children, omit, Show } from "solid-js"
import { dynamic } from "@solidjs/web"
import type { JSX } from "@solidjs/web"
import type { Props } from "./types.solid"

export default function ListItem(props: Props) {
  const rest = omit(
    props,
    "as",
    "borderTop",
    "children",
    "class",
    "description",
    "end",
    "for",
    "headline",
    "inset",
    "start",
    "submenu",
    "text",
    "type",
  )

  const end = children(() => props.end)
  const start = children(() => props.start)
  const text = children(() => props.text)

  const hasLabel = () =>
    props.type === "checkbox" ||
    props.type === "radio" ||
    props.type === "switch"
  const hasText = () => !!(props.headline || props.description || text())
  const tag = () => props.as ?? (props.href ? "a" : undefined)
  const Tag = dynamic(tag)

  const Start = () => (
    <Show when={start()}>
      <div class="ui-start">{start()}</div>
    </Show>
  )
  const End = () => (
    <Show when={end()}>
      <div class="ui-end">{end()}</div>
    </Show>
  )
  const Text = (textProps: { children?: JSX.Element }) => (
    <div class="ui-text">
      <Show when={props.headline}>
        <p>{props.headline}</p>
      </Show>
      <Show when={props.description}>
        <p>{props.description}</p>
      </Show>
      {text()}
      {textProps.children}
    </div>
  )
  const Content = () => (
    <>
      <Start />
      <Show when={hasText()} fallback={props.children}>
        <Text>{props.children}</Text>
      </Show>
      <End />
    </>
  )

  return (
    <li
      class={[
        {
          "ui-border-top": props.borderTop,
          "ui-inset": props.inset,
        },
        props.class,
      ]}
      {...((tag() ? {} : rest) as JSX.HTMLAttributes<HTMLLIElement>)}
    >
      <Show
        when={hasLabel()}
        fallback={
          <Show when={tag()} fallback={<Content />}>
            <Tag {...(rest as JSX.HTMLAttributes<HTMLDivElement>)}>
              <Content />
            </Tag>
          </Show>
        }
      >
        <label class={props.type && `ui-${props.type}`} for={props.for}>
          <Start />
          <Show when={hasText()}>
            <Text />
          </Show>
          <End />
          {props.children}
        </label>
      </Show>
      {props.submenu}
    </li>
  )
}
