// packages/opui/components/ListItem/ListItem.vue
<script setup lang="ts">
import { computed, useAttrs } from "vue"
import type { Props, Slots } from "./types.d.vue"

const props = defineProps<Props>()
const slots = defineSlots<Slots>()
const attrs = useAttrs()

defineOptions({
  inheritAttrs: false,
})

const hasLabel = computed(
  () =>
    props.type &&
    (props.type === "checkbox" ||
      props.type === "radio" ||
      props.type === "switch"),
)
const labelClass = computed(() => props.type || "")
const Tag = computed(() => props.as)

const liAttrs = computed(() => (Tag.value ? {} : attrs))
const innerAttrs = computed(() => (Tag.value ? attrs : {}))
</script>

<template>
  <li
    :class="[
      {
        'border-top': props.borderTop,
        inset: props.inset,
      },
      props.class,
    ]"
    v-bind="liAttrs"
  >
    <label v-if="hasLabel" :class="labelClass" :for="props.for">
      <div v-if="slots.start" class="start">
        <slot name="start"></slot>
      </div>
      <div
        v-if="slots.text || props.headline || props.description"
        class="text"
      >
        <p v-if="props.headline">{{ props.headline }}</p>
        <p v-if="props.description">{{ props.description }}</p>
        <slot name="text"></slot>
      </div>
      <div v-if="slots.end" class="end">
        <slot name="end"></slot>
      </div>
      <slot></slot>
    </label>

    <component :is="Tag" v-else-if="Tag" v-bind="innerAttrs">
      <div v-if="slots.start" class="start">
        <slot name="start"></slot>
      </div>
      <div
        v-if="props.headline || props.description || slots.text"
        class="text"
      >
        <p v-if="props.headline">{{ props.headline }}</p>
        <p v-if="props.description">{{ props.description }}</p>
        <slot name="text"></slot>
        <slot></slot>
      </div>
      <slot v-else></slot>
      <div v-if="slots.end" class="end">
        <slot name="end"></slot>
      </div>
    </component>

    <template v-else>
      <div v-if="slots.start" class="start">
        <slot name="start"></slot>
      </div>
      <div
        v-if="props.headline || props.description || slots.text"
        class="text"
      >
        <p v-if="props.headline">{{ props.headline }}</p>
        <p v-if="props.description">{{ props.description }}</p>
        <slot name="text"></slot>
        <slot></slot>
      </div>
      <slot v-else></slot>
      <div v-if="slots.end" class="end">
        <slot name="end"></slot>
      </div>
    </template>
  </li>
</template>

// packages/opui/components/ListItem/ListItem.svelte
<script lang="ts">
  import type { Props } from "./types.svelte"
  import type { Snippet } from "svelte"

  const props: Props = $props()
  const {
    as: Tag,
    borderTop,
    class: className,
    for: htmlFor,
    inset,
    type,

    // Snippets
    children,
    description,
    end,
    headline,
    start,
    text,
    ...rest
  } = $derived(props)

  let element = $state<HTMLLIElement | null>(null)
  export { element as this }
  const hasLabel = $derived(
    type && ["checkbox", "radio", "switch"].includes(type),
  )
  const labelClass = $derived(`ui-${type}` || "")
</script>

{#snippet snippetString(ss: Snippet | string | undefined)}
  {#if typeof ss === "string"}
    {ss}
  {:else}
    {@render ss?.()}
  {/if}
{/snippet}

{#snippet inner()}
  {#if start}
    <div class="ui-start">
      {@render snippetString(start)}
    </div>
  {/if}
  {#if text || headline || description}
    <div class="ui-text">
      {#if headline}
        <p>{@render snippetString(headline)}</p>
      {/if}
      {#if description}
        <p>{@render snippetString(description)}</p>
      {/if}
      {@render snippetString(text)}
      {@render children?.()}
    </div>
  {:else}
    {@render children?.()}
  {/if}
  {#if end}
    <div class="ui-end">
      {@render snippetString(end)}
    </div>
  {/if}
{/snippet}

<li
  bind:this={element}
  class={[
    {
      "ui-border-top": borderTop,
      "ui-inset": inset,
    },
    className,
  ]}
  {...!(props.as || props.as === "li") ? (rest as typeof props) : {}}
>
  {#if hasLabel}
    <label class={labelClass} for={htmlFor}>
      {@render inner()}
    </label>
  {:else if Tag}
    <svelte:element
      this={Tag}
      {...props.as != "li" ? (rest as typeof props) : {}}
    >
      {@render inner()}
    </svelte:element>
  {:else}
    {@render inner()}
  {/if}
</li>
