// src/component-examples/text-field/Headers.vue
<script setup lang="ts">
import { TextField } from "opui-css/vue"
</script>

<template>
  <TextField label="Username" placeholder="Enter your name">
    <template #header>Full Name</template>
  </TextField>

  <TextField label="Tagline" placeholder="A short description">
    <template #footer>0 / 80</template>
  </TextField>
</template>

// src/component-examples/text-field/Headers.tsx
import { TextField } from "opui-css/solid"

export default function Example() {
  return (
    <>
      <TextField
        label="Username"
        placeholder="Enter your name"
        header="Full Name"
      />

      <TextField
        label="Tagline"
        placeholder="A short description"
        footer="0 / 80"
      />
    </>
  )
}
