// src/component-examples/text-field/Headers.vue
<script setup lang="ts">
import { TextField } from "opui-css/vue"
</script>

<template>
  <TextField label="Username" placeholder="Enter your name">
    <template #header>Full Name</template>
  </TextField>

  <TextField label="Tagline" placeholder="A short description">
    <template #footer>0 / 80</template>
  </TextField>
</template>

// src/component-examples/text-field/Headers.svelte
<script lang="ts">
  import { TextField } from "opui-css/svelte"
</script>

<TextField label="Username" placeholder="Enter your name">
  {#snippet header()}Full Name{/snippet}
</TextField>

<TextField label="Tagline" placeholder="A short description">
  {#snippet footer()}0 / 80{/snippet}
</TextField>
