// src/component-examples/text-field/InputTypes.vue
<script setup lang="ts"></script>

<template>
  <div class="example-column">
    <label class="ui-text-field input-type-field">
      <span class="ui-label">Color</span>
      <input type="color" placeholder="Color" />
    </label>
    <label class="ui-text-field input-type-field">
      <span class="ui-label">Email</span>
      <input type="email" placeholder="name@email.com" />
    </label>
    <label class="ui-text-field input-type-field">
      <span class="ui-label">Password</span>
      <input type="password" placeholder="Password" />
    </label>
    <label class="ui-text-field input-type-field">
      <span class="ui-label">Search</span>
      <input type="search" placeholder="Search" />
    </label>
    <label class="ui-text-field input-type-field">
      <span class="ui-label">Phone</span>
      <input type="tel" placeholder="(666) 666-1337" />
    </label>
    <label class="ui-text-field input-type-field">
      <span class="ui-label">Text</span>
      <input type="text" placeholder="Text" />
    </label>
    <label class="ui-text-field input-type-field">
      <span class="ui-label">URL</span>
      <input type="url" placeholder="https://yoursite.com" />
    </label>
  </div>

  <div class="example-column">
    <label class="ui-text-field input-type-field">
      <span class="ui-label">Date</span>
      <input type="date" placeholder="Date" />
    </label>
    <label class="ui-text-field input-type-field">
      <span class="ui-label">Datetime local</span>
      <input type="datetime-local" placeholder="Datetime local" />
    </label>
    <label class="ui-text-field input-type-field">
      <span class="ui-label">Month</span>
      <input type="month" placeholder="Month" />
    </label>
    <label class="ui-text-field input-type-field">
      <span class="ui-label">Time</span>
      <input type="time" placeholder="Time" />
    </label>
    <label class="ui-text-field input-type-field">
      <span class="ui-label">Week</span>
      <input type="week" placeholder="Week" />
    </label>
  </div>
</template>

// src/component-examples/text-field/InputTypes.svelte
<div class="example-column">
  <label class="ui-text-field input-type-field">
    <span class="ui-label">Color</span>
    <span class="ui-field">
      <input type="color" placeholder="Color" />
    </span>
  </label>
  <label class="ui-text-field input-type-field">
    <span class="ui-label">Email</span>
    <span class="ui-field">
      <input type="email" placeholder="name@email.com" />
    </span>
  </label>
  <label class="ui-text-field input-type-field">
    <span class="ui-label">Password</span>
    <span class="ui-field">
      <input type="password" placeholder="Password" />
    </span>
  </label>
  <label class="ui-text-field input-type-field">
    <span class="ui-label">Search</span>
    <span class="ui-field">
      <input type="search" placeholder="Search" />
    </span>
  </label>
  <label class="ui-text-field input-type-field">
    <span class="ui-label">Phone</span>
    <span class="ui-field">
      <input type="tel" placeholder="(666) 666-1337" />
    </span>
  </label>
  <label class="ui-text-field input-type-field">
    <span class="ui-label">Text</span>
    <span class="ui-field">
      <input type="text" placeholder="Text" />
    </span>
  </label>
  <label class="ui-text-field input-type-field">
    <span class="ui-label">URL</span>
    <span class="ui-field">
      <input type="url" placeholder="https://yoursite.com" />
    </span>
  </label>
</div>

<div class="example-column">
  <label class="ui-text-field input-type-field">
    <span class="ui-label">Date</span>
    <span class="ui-field">
      <input type="date" placeholder="Date" />
    </span>
  </label>
  <label class="ui-text-field input-type-field">
    <span class="ui-label">Datetime local</span>
    <span class="ui-field">
      <input type="datetime-local" placeholder="Datetime local" />
    </span>
  </label>
  <label class="ui-text-field input-type-field">
    <span class="ui-label">Month</span>
    <span class="ui-field">
      <input type="month" placeholder="Month" />
    </span>
  </label>
  <label class="ui-text-field input-type-field">
    <span class="ui-label">Time</span>
    <span class="ui-field">
      <input type="time" placeholder="Time" />
    </span>
  </label>
  <label class="ui-text-field input-type-field">
    <span class="ui-label">Week</span>
    <span class="ui-field">
      <input type="week" placeholder="Week" />
    </span>
  </label>
</div>
