// src/component-examples/text-field/InputTypes.svelte
<div class="example-column">
  <label class="ui-text-field input-type-field">
    <span class="ui-label">Color</span>
    <span class="ui-field">
      <input type="color" placeholder="Color" />
    </span>
  </label>
  <label class="ui-text-field input-type-field">
    <span class="ui-label">Email</span>
    <span class="ui-field">
      <input type="email" placeholder="name@email.com" />
    </span>
  </label>
  <label class="ui-text-field input-type-field">
    <span class="ui-label">Password</span>
    <span class="ui-field">
      <input type="password" placeholder="Password" />
    </span>
  </label>
  <label class="ui-text-field input-type-field">
    <span class="ui-label">Search</span>
    <span class="ui-field">
      <input type="search" placeholder="Search" />
    </span>
  </label>
  <label class="ui-text-field input-type-field">
    <span class="ui-label">Phone</span>
    <span class="ui-field">
      <input type="tel" placeholder="(666) 666-1337" />
    </span>
  </label>
  <label class="ui-text-field input-type-field">
    <span class="ui-label">Text</span>
    <span class="ui-field">
      <input type="text" placeholder="Text" />
    </span>
  </label>
  <label class="ui-text-field input-type-field">
    <span class="ui-label">URL</span>
    <span class="ui-field">
      <input type="url" placeholder="https://yoursite.com" />
    </span>
  </label>
</div>

<div class="example-column">
  <label class="ui-text-field input-type-field">
    <span class="ui-label">Date</span>
    <span class="ui-field">
      <input type="date" placeholder="Date" />
    </span>
  </label>
  <label class="ui-text-field input-type-field">
    <span class="ui-label">Datetime local</span>
    <span class="ui-field">
      <input type="datetime-local" placeholder="Datetime local" />
    </span>
  </label>
  <label class="ui-text-field input-type-field">
    <span class="ui-label">Month</span>
    <span class="ui-field">
      <input type="month" placeholder="Month" />
    </span>
  </label>
  <label class="ui-text-field input-type-field">
    <span class="ui-label">Time</span>
    <span class="ui-field">
      <input type="time" placeholder="Time" />
    </span>
  </label>
  <label class="ui-text-field input-type-field">
    <span class="ui-label">Week</span>
    <span class="ui-field">
      <input type="week" placeholder="Week" />
    </span>
  </label>
</div>

// src/component-examples/text-field/InputTypes.tsx
import { TextField } from "opui-css/solid"

export default function Example() {
  return (
    <>
      <TextField label="Text" type="text" placeholder="Text input" />
      <TextField label="Email" type="email" placeholder="email@example.com" />
      <TextField label="Password" type="password" placeholder="Password" />
      <TextField label="Number" type="number" placeholder="0" />
    </>
  )
}
