// packages/opui/components/ToggleGroup/ToggleGroup.svelte
<script lang="ts">
  import type { Props } from "./types.svelte"
  import { setToggleGroupContext } from "./context"

  let {
    children,
    class: className,
    name,
    orientation,
    ref = $bindable(null),
    selection = "multiple",
    size = "default",
    ...rest
  }: Props = $props()

  const id = $props.id()

  setToggleGroupContext({
    get groupName() {
      return name || `toggle-group-${id}`
    },
    get inputType() {
      return selection === "single" ? "radio" : "checkbox"
    },
  })
</script>

<div
  bind:this={ref}
  class={[
    "ui-toggle-group",
    size !== "default" && size && `ui-${size}`,
    orientation && `ui-${orientation}`,
    className,
  ]}
  role={selection === "single" ? "radiogroup" : "group"}
  {...rest}
>
  {@render children()}
</div>

// packages/opui/components/ToggleGroup/ToggleGroup.vue
<script setup lang="ts">
import { provide, useId } from "vue";
import { type Props, ToggleGroupKey } from "./types";

const {
	name,
	orientation,
	selection = "multiple",
	size = "default",
} = defineProps<Props>();

defineOptions({
	inheritAttrs: false,
});

const groupName = name || useId();
const inputType = selection === "single" ? "radio" : "checkbox";

provide(ToggleGroupKey, { name: groupName, type: inputType });
</script>

<template>
  <div
    :class="[
      'toggle-group',
      size !== 'default' && size,
      orientation,
      $props.class,
    ]"
    :role="selection === 'single' ? 'radiogroup' : 'group'"
    v-bind="$attrs"
  >
    <slot></slot>
  </div>
</template>
