// packages/opui/components/Stepper/Stepper.svelte
<script lang="ts">
  import type { Props } from "./types.svelte"
  import { cssString } from "./css-string"

  let {
    class: className,
    complete,
    completedLabel,
    current,
    items,
    label,
    orientation,
    size,
    style,

    // Snippets
    check,
    children,
    ...rest
  }: Props = $props()

  let done = $derived(
    complete ||
      (current !== undefined && items !== undefined && current >= items.length),
  )
</script>

<ol
  aria-label={label}
  class={[
    "ui-stepper",
    { "ui-complete": done, "ui-vertical": orientation === "vertical" },
    size && `ui-${size}`,
    className,
  ]}
  style={[
    completedLabel && `--_completed-label: ${cssString(completedLabel)};`,
    style,
  ]
    .filter(Boolean)
    .join(" ") || undefined}
  {...rest}
>
  {#each items ?? [] as { description, href, label: stepLabel }, index (index)}
    <li aria-current={index === current ? "step" : undefined}>
      {#if check}
        <span aria-hidden="true" class="ui-check">{@render check()}</span>
      {/if}
      {#if href && (done || (current !== undefined && index < current))}
        <a {href}>{stepLabel}</a>
      {:else}
        {stepLabel}
      {/if}
      {#if description}
        <span class="ui-description">{description}</span>
      {/if}
    </li>
  {/each}
  {@render children?.()}
</ol>

// packages/opui/components/Stepper/Stepper.vue
<script setup lang="ts">
import { computed } from "vue"
import { cssString } from "./css-string"
import type { Props, Slots } from "./types.d.vue"

const { complete, completedLabel, current, items, label, orientation, size } =
  defineProps<Props>()
const slots = defineSlots<Slots>()

const done = computed(
  () =>
    complete ||
    (current !== undefined && items !== undefined && current >= items.length),
)

const completedLabelStyle = computed(() =>
  completedLabel
    ? { "--_completed-label": cssString(completedLabel) }
    : undefined,
)
</script>

<template>
  <ol
    :aria-label="label"
    :class="[
      'ui-stepper',
      { 'ui-complete': done, 'ui-vertical': orientation === 'vertical' },
      size && `ui-${size}`,
      $props.class,
    ]"
    :style="completedLabelStyle"
  >
    <li
      v-for="({ description, href, label: stepLabel }, index) in items"
      :key="index"
      :aria-current="index === current ? 'step' : undefined"
    >
      <span v-if="slots.check" aria-hidden="true" class="ui-check"
        ><slot name="check"></slot></span
      ><a
        v-if="href && (done || (current !== undefined && index < current))"
        :href="href"
        >{{ stepLabel }}</a
      ><template v-else>{{ stepLabel }}</template
      ><span v-if="description" class="ui-description">{{ description }}</span>
    </li>
    <slot></slot>
  </ol>
</template>
