// src/component-examples/anchor/Hover.vue
<script setup lang="ts">
import { Anchor } from "opui-css/vue"
</script>

<template>
  <Anchor trigger="hover" id="anchor-hover">
    <button
      interestfor="anchor-hover"
      commandfor="anchor-hover"
      command="toggle-popover"
    >
      Hover me
    </button>
    <template #anchored
      ><span><div class="card elevated">Tooltip content</div></span></template
    >
  </Anchor>
</template>

// src/component-examples/anchor/Hover.svelte
<script lang="ts">
  import { Anchor } from "@opui/svelte"
  import { Button } from "@opui/svelte"
</script>

<Anchor trigger="hover" id="anchor-hover">
  <Button
    interestfor="anchor-hover"
    commandfor="anchor-hover"
    command="toggle-popover">Hover me</Button
  >
  {#snippet anchored()}
    <span><div class="ui-card ui-elevated">Tooltip content</div></span>
  {/snippet}
</Anchor>
