// packages/opui/components/FieldGroup/FieldGroup.vue
<script setup lang="ts">
import type { FieldGroupProps } from './types.ts'
import { provide } from 'vue'

const props = defineProps<FieldGroupProps>()

if (props.name) {
  provide('currentFieldName', props.name)
}
</script>

<template>
  <div :class="['field-group', props.direction, props.class]" v-bind="$attrs" role="group">
    <slot></slot>
  </div>
</template>

// packages/opui/components/FieldGroup/FieldGroup.svelte
<script lang="ts">
  import type { Props } from "./types.svelte"
  export const title = "Field Group" as const

  const {
    children,
    class: className,
    direction,
    name,
    ...rest
  }: Props = $props()

  // TODO: currentFieldName

  let element = $state<HTMLDivElement | null>(null)
  export { element as this }
</script>

<div
  bind:this={element}
  class={["field-group", direction, className]}
  {...rest}
  role="group"
>
  {@render children?.()}
</div>
