// src/component-examples/button/Keyboard.vue
<script setup lang="ts">
import { Button } from "opui-css/vue"
</script>

<template>
<Button>
  Search <kbd>⌘K</kbd>
</Button>
<Button variant="outlined">
  Save <kbd>⌘S</kbd>
</Button>
<Button variant="tonal">
  Copy <kbd>⌘C</kbd>
</Button>
<Button variant="filled">
  Delete <kbd>⌘⌫</kbd>
</Button>
</template>

// src/component-examples/button/Keyboard.tsx
import { Button } from "opui-css/solid"

export default function Example() {
  return (
    <>
      <Button>
        Search <kbd>⌘K</kbd>
      </Button>
      <Button variant="outlined">
        Save <kbd>⌘S</kbd>
      </Button>
      <Button variant="tonal">
        Copy <kbd>⌘C</kbd>
      </Button>
      <Button variant="filled">
        Delete <kbd>⌘⌫</kbd>
      </Button>
    </>
  )
}
