// src/component-examples/callout/Severities.svelte
<script lang="ts">
  import { Callout } from "opui-css/svelte"
</script>

<Callout severity="neutral">This is a tonal neutral Callout</Callout>
<Callout severity="info">This is a tonal info Callout</Callout>
<Callout severity="success">This is a tonal success Callout</Callout>
<Callout severity="warning">This is a tonal warning Callout</Callout>
<Callout severity="critical">This is a tonal critical Callout</Callout>
<Callout severity="neutral" variant="outlined"
  >This is an outlined neutral Callout</Callout
>
<Callout severity="info" variant="outlined"
  >This is an outlined info Callout</Callout
>
<Callout severity="success" variant="outlined"
  >This is an outlined success Callout</Callout
>
<Callout severity="warning" variant="outlined"
  >This is an outlined warning Callout</Callout
>
<Callout severity="critical" variant="outlined"
  >This is an outlined critical Callout</Callout
>

// src/component-examples/callout/Severities.vue
<script setup lang="ts">
import { Callout } from "opui-css/vue"
</script>

<template>
  <Callout severity="neutral">This is a tonal neutral Callout</Callout>
  <Callout severity="info">This is a tonal info Callout</Callout>
  <Callout severity="success">This is a tonal success Callout</Callout>
  <Callout severity="warning">This is a tonal warning Callout</Callout>
  <Callout severity="critical">This is a tonal critical Callout</Callout>
  <Callout severity="neutral" variant="outlined"
    >This is an outlined neutral Callout</Callout
  >
  <Callout severity="info" variant="outlined"
    >This is an outlined info Callout</Callout
  >
  <Callout severity="success" variant="outlined"
    >This is an outlined success Callout</Callout
  >
  <Callout severity="warning" variant="outlined"
    >This is an outlined warning Callout</Callout
  >
  <Callout severity="critical" variant="outlined"
    >This is an outlined critical Callout</Callout
  >
</template>
