// packages/opui/components/Tooltip/Tooltip.tsx
import { omit } from "solid-js"
import Anchor from "../Anchor/Anchor"
import type { Props } from "./types.solid"

export default function Tooltip(props: Props) {
  const rest = omit(
    props,
    "alignment",
    "arrow",
    "children",
    "class",
    "content",
    "id",
    "label",
  )

  return (
    <Anchor
      alignment={props.alignment}
      anchored={
        <>
          {props.label}
          {props.content}
        </>
      }
      class={["ui-tooltip", { "ui-with-arrow": !!props.arrow }, props.class]}
      id={props.id}
      trigger="hover"
      {...rest}
    >
      {props.children}
    </Anchor>
  )
}

// packages/opui/components/Tooltip/Tooltip.vue
<script setup lang="ts">
import Anchor from "../Anchor/Anchor.vue";
import type { Props } from "./types";

const { alignment, arrow, id, label } = defineProps<Props>();
</script>

<template>
  <Anchor
    :alignment="alignment"
    :class="['tooltip', { 'with-arrow': arrow }, $props.class]"
    :id="id"
    trigger="hover"
  >
    <slot></slot>
    <template #anchored>
      {{ label }}
      <slot name="content"></slot>
    </template>
  </Anchor>
</template>
