// packages/opui/components/Tooltip/Tooltip.tsx
import { omit } from "solid-js"
import Anchor from "../Anchor/Anchor"
import type { Props } from "./types.solid"

export default function Tooltip(props: Props) {
  const rest = omit(
    props,
    "alignment",
    "arrow",
    "children",
    "class",
    "content",
    "id",
    "label",
  )

  return (
    <Anchor
      alignment={props.alignment}
      anchored={
        <>
          {props.label}
          {props.content}
        </>
      }
      class={["ui-tooltip", { "ui-with-arrow": !!props.arrow }, props.class]}
      id={props.id}
      trigger="hover"
      {...rest}
    >
      {props.children}
    </Anchor>
  )
}

// packages/opui/components/Tooltip/Tooltip.svelte
<script lang="ts">
  import Anchor from "../Anchor/Anchor.svelte"
  import type { Props } from "./types.svelte"

  let {
    alignment,
    arrow,
    class: className,
    id,
    label,

    // Snippets
    children,
    content,
    ...rest
  }: Props = $props()
</script>

<Anchor
  {alignment}
  class={["ui-tooltip", { "ui-with-arrow": arrow }, className]}
  {id}
  trigger="hover"
  {...rest}
>
  {@render children?.()}
  {#snippet anchored()}
    {label}
    {@render content?.()}
  {/snippet}
</Anchor>
