// src/component-examples/table/Dense.tsx
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeaderCell,
  TableRow,
} from "opui-css/solid"

export default function Example() {
  return (
    <Table variant="dense">
      <caption>Band Members</caption>
      <TableHead>
        <TableRow>
          <TableHeaderCell>Band</TableHeaderCell>
          <TableHeaderCell>Name</TableHeaderCell>
          <TableHeaderCell>Instrument</TableHeaderCell>
        </TableRow>
      </TableHead>
      <TableBody>
        <TableRow>
          <TableCell>Radiohead</TableCell>
          <TableCell>Ed O'Brien</TableCell>
          <TableCell>Guitar/Vocals</TableCell>
        </TableRow>
        <TableRow>
          <TableCell>Korn</TableCell>
          <TableCell>Jonathan Davis</TableCell>
          <TableCell>Vocals</TableCell>
        </TableRow>
        <TableRow>
          <TableCell>Broken Bells</TableCell>
          <TableCell>James Mercer</TableCell>
          <TableCell>Vocals/Guitar</TableCell>
        </TableRow>
        <TableRow>
          <TableCell>Pink Floyd</TableCell>
          <TableCell>David Gilmour</TableCell>
          <TableCell>Guitar/Vocals</TableCell>
        </TableRow>
      </TableBody>
      <tfoot>
        <TableRow>
          <TableCell colspan={3}>All great bands!</TableCell>
        </TableRow>
      </tfoot>
    </Table>
  )
}

// src/component-examples/table/Dense.svelte
<script lang="ts">
  import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeaderCell,
    TableRow,
  } from "@opui/svelte"
</script>

<Table variant="dense">
  <caption>Band Members</caption>
  <TableHead>
    <TableRow>
      <TableHeaderCell>Band</TableHeaderCell>
      <TableHeaderCell>Name</TableHeaderCell>
      <TableHeaderCell>Instrument</TableHeaderCell>
    </TableRow>
  </TableHead>
  <TableBody>
    <TableRow>
      <TableCell>Radiohead</TableCell>
      <TableCell>Ed O'Brien</TableCell>
      <TableCell>Guitar/Vocals</TableCell>
    </TableRow>
    <TableRow>
      <TableCell>Korn</TableCell>
      <TableCell>Jonathan Davis</TableCell>
      <TableCell>Vocals</TableCell>
    </TableRow>
    <TableRow>
      <TableCell>Broken Bells</TableCell>
      <TableCell>James Mercer</TableCell>
      <TableCell>Vocals/Guitar</TableCell>
    </TableRow>
    <TableRow>
      <TableCell>Pink Floyd</TableCell>
      <TableCell>David Gilmour</TableCell>
      <TableCell>Guitar/Vocals</TableCell>
    </TableRow>
  </TableBody>
  <tfoot>
    <TableRow>
      <TableCell colspan={3}>All great bands!</TableCell>
    </TableRow>
  </tfoot>
</Table>
