// src/component-examples/tooltip/Arrow.vue
<script setup lang="ts">
import { Button, Tooltip } from "opui-css/vue"
</script>

<template>
  <Tooltip arrow label="Save your changes" id="tooltip-arrow">
    <Button
      interestfor="tooltip-arrow"
      commandfor="tooltip-arrow"
      command="toggle-popover"
      >Save</Button
    >
  </Tooltip>
</template>

// src/component-examples/tooltip/Arrow.tsx
import { Button, Tooltip } from "opui-css/solid"

export default function Example() {
  return (
    <Tooltip arrow label="Save your changes" id="tooltip-arrow">
      <Button
        interestfor="tooltip-arrow"
        commandfor="tooltip-arrow"
        command="toggle-popover"
      >
        Save
      </Button>
    </Tooltip>
  )
}
