// src/component-examples/tooltip/RichContent.tsx
import { Button, Tooltip } from "opui-css/solid"

export default function Example() {
  return (
    <Tooltip
      id="tooltip-rich"
      content={
        <>
          Press <kbd>⌘</kbd> + <kbd>K</kbd> to open the command palette.
        </>
      }
    >
      <Button
        interestfor="tooltip-rich"
        commandfor="tooltip-rich"
        command="toggle-popover"
      >
        Keyboard shortcuts
      </Button>
    </Tooltip>
  )
}

// src/component-examples/tooltip/RichContent.vue
<script setup lang="ts">
import { Button, Tooltip } from "opui-css/vue"
</script>

<template>
  <Tooltip id="tooltip-rich">
    <Button
      interestfor="tooltip-rich"
      commandfor="tooltip-rich"
      command="toggle-popover"
      >Keyboard shortcuts</Button
    >
    <template #content>
      Press <kbd>⌘</kbd> + <kbd>K</kbd> to open the command palette.
    </template>
  </Tooltip>
</template>
