// packages/opui/components/Checkbox/Checkbox.svelte
<script lang="ts">
  import CheckboxInput from "./CheckboxInput.svelte"
  import { getFieldContext } from "../FieldGroup/context"
  import type { CheckboxProps as Props } from "./types.svelte"

  let {
    checked = $bindable(),
    class: className,
    error,
    group = $bindable(),
    hideLabel,
    name,
    ref = $bindable(null),
    size,
    spread,
    stack,

    // Snippets
    children,
    endText,
    ...rest
  }: Props = $props()

  const id = $props.id()
  const field = getFieldContext()
  const endTextId = $derived(endText ? `end-text-${id}` : undefined)
</script>

<label
  bind:this={ref}
  class={[
    "ui-checkbox",
    size && `ui-${size}`,
    {
      "ui-stack": stack,
      "ui-spread": spread,
    },
    className,
  ]}
  data-invalid={error || undefined}
>
  <CheckboxInput
    aria-describedby={endTextId}
    bind:checked
    bind:group
    name={name || field?.name}
    {...rest}
  />
  <span class={[hideLabel ? "ui-sr-only" : "ui-label"]}>
    {@render children?.()}
  </span>
  {#if endText}
    <span id={endTextId} class="ui-end-text">
      {#if typeof endText === "string"}
        {endText}
      {:else}
        {@render endText()}
      {/if}
    </span>
  {/if}
</label>

// packages/opui/components/Checkbox/Checkbox.tsx
import { createUniqueId, omit, Show, useContext } from "solid-js"
import { FieldGroupContext } from "../FieldGroup/context"
import CheckboxInput from "./CheckboxInput"
import type { CheckboxProps } from "./types.solid"

export default function Checkbox(props: CheckboxProps) {
  const rest = omit(
    props,
    "children",
    "class",
    "endText",
    "error",
    "hideLabel",
    "name",
    "size",
    "spread",
    "stack",
  )

  const fieldGroup = useContext(FieldGroupContext)
  const id = createUniqueId()
  const endTextId = () => (props.endText ? id : undefined)

  return (
    <label
      class={[
        "ui-checkbox",
        props.size && `ui-${props.size}`,
        {
          "ui-spread": !!props.spread,
          "ui-stack": !!props.stack,
        },
        props.class,
      ]}
      data-invalid={props.error || undefined}
    >
      <CheckboxInput
        aria-describedby={endTextId()}
        name={props.name || fieldGroup.name}
        {...rest}
      />
      <span class={[props.hideLabel ? "ui-sr-only" : "ui-label"]}>
        {props.children}
      </span>
      <Show when={props.endText}>
        <span id={endTextId()} class="ui-end-text">
          {props.endText}
        </span>
      </Show>
    </label>
  )
}
