// packages/opui/components/Checkbox/CheckboxInput.vue
<script setup lang="ts">
import type { CheckboxInputProps } from "./types"
import { useAttrs, useTemplateRef, watchPostEffect } from "vue"

defineOptions({
  inheritAttrs: false,
})

const attrs = useAttrs()
const props = defineProps<CheckboxInputProps>()
const modelValue = defineModel<boolean | (string | number)[]>()

const input = useTemplateRef<HTMLInputElement>("input")

if (modelValue.value === undefined && attrs.checked !== undefined) {
  modelValue.value = attrs.checked !== false
}

watchPostEffect(() => {
  if (input.value) input.value.indeterminate = Boolean(props.indeterminate)
})
</script>

<template>
  <input
    ref="input"
    type="checkbox"
    :data-indeterminate="props.indeterminate || undefined"
    v-bind="$attrs"
    v-model="modelValue"
  />
</template>

// packages/opui/components/Checkbox/CheckboxInput.svelte
<script lang="ts">
  import type { CheckboxInputProps as Props } from "./types.svelte"

  let {
    checked = $bindable(),
    indeterminate = $bindable(),
    ...rest
  }: Props = $props()
  let element = $state<HTMLInputElement | null>(null)
  export { element as this }
</script>

<input
  bind:this={element}
  bind:checked
  bind:indeterminate
  type="checkbox"
  data-indeterminate={indeterminate || undefined}
  {...rest}
/>
