// packages/opui/components/Checkbox/CheckboxInput.tsx
import { omit } from "solid-js"
import type { CheckboxInputProps } from "./types.solid"

export default function CheckboxInput(props: CheckboxInputProps) {
  const rest = omit(props, "indeterminate")

  return (
    <input
      type="checkbox"
      data-indeterminate={props.indeterminate || undefined}
      prop:indeterminate={!!props.indeterminate}
      {...rest}
    />
  )
}

// packages/opui/components/Checkbox/CheckboxInput.svelte
<script lang="ts">
  import type { CheckboxInputProps as Props } from "./types.svelte"

  let {
    checked = $bindable(),
    indeterminate = $bindable(),
    ...rest
  }: Props = $props()
  let element = $state<HTMLInputElement | null>(null)
  export { element as this }
</script>

<input
  bind:this={element}
  bind:checked
  bind:indeterminate
  type="checkbox"
  data-indeterminate={indeterminate || undefined}
  {...rest}
/>
