// packages/opui/components/Card/Card.vue
<script setup lang="ts">
import type { Props, Slots } from "./types.d.vue"

const { actionsAlign, variant } = defineProps<Props>()
const slots = defineSlots<Slots>()
</script>

<template>
  <div :class="['ui-card', variant && `ui-${variant}`, $props.class]">
    <hgroup v-if="slots.header">
      <slot name="header"></slot>
    </hgroup>

    <div v-if="slots.content" class="ui-content">
      <slot name="content"></slot>
    </div>

    <slot></slot>

    <div
      v-if="slots.actions"
      :class="['ui-actions', actionsAlign && `ui-align-${actionsAlign}`]"
    >
      <slot name="actions"></slot>
    </div>
  </div>
</template>

// packages/opui/components/Card/Card.svelte
<script lang="ts">
  import type { Props } from "./types.svelte"

  let {
    actionsAlign,
    class: className,
    ref = $bindable(null),
    variant,

    // Snippets
    actions,
    children,
    content,
    header,
    ...rest
  }: Props = $props()
</script>

<div
  bind:this={ref}
  class={["ui-card", variant && `ui-${variant}`, className]}
  {...rest}
>
  {#if header}
    <hgroup>
      {@render header()}
    </hgroup>
  {/if}

  {#if content}
    <div class="ui-content">
      {@render content()}
    </div>
  {/if}

  {@render children?.()}

  {#if actions}
    <div class={["ui-actions", actionsAlign && `ui-align-${actionsAlign}`]}>
      {@render actions()}
    </div>
  {/if}
</div>
