// packages/opui/components/Card/Card.svelte
<script lang="ts">
  import type { Props } from "./types.svelte"

  let {
    actionsAlign,
    class: className,
    ref = $bindable(null),
    variant,

    // Snippets
    actions,
    children,
    content,
    header,
    ...rest
  }: Props = $props()
</script>

<div
  bind:this={ref}
  class={["ui-card", variant && `ui-${variant}`, className]}
  {...rest}
>
  {#if header}
    <hgroup>
      {@render header()}
    </hgroup>
  {/if}

  {#if content}
    <div class="ui-content">
      {@render content()}
    </div>
  {/if}

  {@render children?.()}

  {#if actions}
    <div class={["ui-actions", actionsAlign && `ui-align-${actionsAlign}`]}>
      {@render actions()}
    </div>
  {/if}
</div>

// packages/opui/components/Card/Card.tsx
import { omit, Show } from "solid-js"
import type { Props } from "./types.solid"

export default function Card(props: Props) {
  const rest = omit(
    props,
    "actions",
    "actionsAlign",
    "children",
    "class",
    "content",
    "header",
    "variant",
  )

  return (
    <div
      class={["ui-card", props.variant && `ui-${props.variant}`, props.class]}
      {...rest}
    >
      <Show when={props.header}>
        <hgroup>{props.header}</hgroup>
      </Show>

      <Show when={props.content}>
        <div class="ui-content">{props.content}</div>
      </Show>

      {props.children}

      <Show when={props.actions}>
        <div
          class={[
            "ui-actions",
            props.actionsAlign && `ui-align-${props.actionsAlign}`,
          ]}
        >
          {props.actions}
        </div>
      </Show>
    </div>
  )
}
