// src/component-examples/tabs/Basics.tsx
import { Tabs, TabsItem, TabsPanel, TabsTab } from "opui-css/solid"

export default function Example() {
  return (
    <Tabs name="basic-tabs">
      <TabsItem open>
        <TabsTab>Profile</TabsTab>
        <TabsPanel>Profile settings and information.</TabsPanel>
      </TabsItem>
      <TabsItem>
        <TabsTab>Settings</TabsTab>
        <TabsPanel>General account settings.</TabsPanel>
      </TabsItem>
      <TabsItem>
        <TabsTab>Notifications</TabsTab>
        <TabsPanel>Manage your notifications.</TabsPanel>
      </TabsItem>
    </Tabs>
  )
}

// src/component-examples/tabs/Basics.svelte
<script lang="ts">
  import { Tabs, TabsItem, TabsPanel, TabsTab } from "opui-css/svelte"
</script>

<Tabs name="basic-tabs">
  <TabsItem open>
    <TabsTab>Profile</TabsTab>
    <TabsPanel>Profile settings and information.</TabsPanel>
  </TabsItem>
  <TabsItem>
    <TabsTab>Settings</TabsTab>
    <TabsPanel>General account settings.</TabsPanel>
  </TabsItem>
  <TabsItem>
    <TabsTab>Notifications</TabsTab>
    <TabsPanel>Manage your notifications.</TabsPanel>
  </TabsItem>
</Tabs>
