// src/component-examples/form/FieldsetStacked.svelte
<script lang="ts">
  import {
    FieldDescription,
    FieldGroup,
    FieldLegend,
    FieldSet,
    Radio,
  } from "opui-css/svelte"
</script>

<FieldSet>
  <FieldLegend>Favorite Pet</FieldLegend>
  <FieldDescription>Please select your favorite type of pet.</FieldDescription>
  <FieldGroup name="pet">
    <Radio value="dog">Dog</Radio>
    <Radio value="cat">Cat</Radio>
    <Radio value="hamster">Hamster</Radio>
  </FieldGroup>
</FieldSet>

// src/component-examples/form/FieldsetStacked.tsx
import {
  FieldDescription,
  FieldGroup,
  FieldLegend,
  FieldSet,
  Radio,
} from "opui-css/solid"

export default function Example() {
  return (
    <FieldSet>
      <FieldLegend>Favorite Pet</FieldLegend>
      <FieldDescription>
        Please select your favorite type of pet.
      </FieldDescription>
      <FieldGroup name="pet">
        <Radio value="dog">Dog</Radio>
        <Radio value="cat">Cat</Radio>
        <Radio value="hamster">Hamster</Radio>
      </FieldGroup>
    </FieldSet>
  )
}
