// src/component-examples/form/Usage.svelte
<script lang="ts">
  import {
    FieldDescription,
    FieldGroup,
    FieldLegend,
    FieldSet,
    Form,
  } from "opui-css/svelte"
</script>

<Form>
  <FieldSet>
    <FieldLegend><!-- --></FieldLegend>
    <FieldDescription><!-- --></FieldDescription>
    <FieldGroup>
      <!-- -->
    </FieldGroup>
    <FieldGroup>
      <!-- -->
    </FieldGroup>
  </FieldSet>
</Form>

// src/component-examples/form/Usage.tsx
import {
  FieldDescription,
  FieldGroup,
  FieldLegend,
  FieldSet,
  Form,
} from "opui-css/solid"

export default function Example() {
  return (
    <>
      <Form>
        <FieldSet>
          <FieldLegend>{/* */}</FieldLegend>
          <FieldDescription>{/* */}</FieldDescription>
          <FieldGroup>{/* */}</FieldGroup>
          <FieldGroup>{/* */}</FieldGroup>
        </FieldSet>
      </Form>

      {/* or */}

      <Form as="div">
        <FieldSet as="div">
          <FieldLegend as="p">{/* */}</FieldLegend>
          <FieldDescription>{/* */}</FieldDescription>
          <FieldGroup>{/* */}</FieldGroup>
          <FieldGroup>{/* */}</FieldGroup>
        </FieldSet>
      </Form>
    </>
  )
}
