// packages/opui/components/Progress/Progress.tsx
import { omit } from "solid-js"
import type { Props } from "./types.solid"

export default function Progress(props: Props) {
  const rest = omit(
    props,
    "aria-busy",
    "aria-describedby",
    "aria-label",
    "children",
    "class",
    "id",
    "max",
    "value",
    "variant",
  )

  return (
    <div
      class={[
        "ui-progress",
        props.variant && `ui-${props.variant}`,
        props.class,
      ]}
    >
      <progress
        aria-busy={props["aria-busy"]}
        aria-describedby={props["aria-describedby"]}
        aria-label={props["aria-label"]}
        id={props.id}
        max={props.max}
        value={props.value}
        {...rest}
      >
        {props.children}
      </progress>
    </div>
  )
}

// packages/opui/components/Progress/Progress.vue
<script setup lang="ts">
import type { Props } from './types'

const {
  'aria-busy': ariaBusy,
  'aria-describedby': ariaDescribedby,
  'aria-label': ariaLabel,
  id,
  max,
  value,
  variant,
} = defineProps<Props>()
</script>

<template>
  <progress
    :aria-busy="ariaBusy"
    :aria-describedby="ariaDescribedby"
    :aria-label="ariaLabel"
    :class="['progress', variant, $props.class]"
    :id="id"
    :max="max"
    :value="value"
  >
    <slot></slot>
  </progress>
</template>
