// packages/opui/components/DescriptionList/DescriptionList.svelte
<script lang="ts">
  import type { Props } from "./types.svelte"

  let {
    bordered,
    children,
    class: className,
    ref = $bindable(null),
    ...rest
  }: Props = $props()
</script>

<dl
  bind:this={ref}
  class={[
    "ui-description-list",
    { "ui-bordered": bordered, "ui-dotted": bordered === "dotted" },
    className,
  ]}
  {...rest}
>
  {@render children?.()}
</dl>

// packages/opui/components/DescriptionList/DescriptionList.vue
<script setup lang="ts">
import type { Props } from './types'

const { bordered } = defineProps<Props>()

defineOptions({
  inheritAttrs: false,
})
</script>

<template>
  <dl
    :class="[
      'description-list',
      { bordered: bordered, dotted: bordered === 'dotted' },
      $props.class,
    ]"
    v-bind="$attrs"
  >
    <slot></slot>
  </dl>
</template>
