// packages/opui/components/DescriptionList/DescriptionList.svelte
<script lang="ts">
  import type { Props } from "./types.svelte"

  let { bordered, children, class: className, ...rest }: Props = $props()
</script>

<dl
  class={[
    "ui-description-list",
    { "ui-bordered": bordered, "ui-dotted": bordered === "dotted" },
    className,
  ]}
  {...rest}
>
  {@render children?.()}
</dl>

// packages/opui/components/DescriptionList/DescriptionList.tsx
import { omit } from "solid-js"
import type { Props } from "./types.solid"

export default function DescriptionList(props: Props) {
  const rest = omit(props, "bordered", "children", "class")

  return (
    <dl
      class={[
        "ui-description-list",
        {
          "ui-bordered": !!props.bordered,
          "ui-dotted": props.bordered === "dotted",
        },
        props.class,
      ]}
      {...rest}
    >
      {props.children}
    </dl>
  )
}
