// packages/opui/components/DescriptionList/Description.tsx
import { omit } from "solid-js"
import type { DescriptionProps } from "./types.solid"

export default function Description(props: DescriptionProps) {
  const rest = omit(props, "children", "class")

  return (
    <dd class={["ui-description", props.class]} {...rest}>
      {props.children}
    </dd>
  )
}

// packages/opui/components/DescriptionList/Description.svelte
<script lang="ts">
  import type { DescriptionProps as Props } from "./types.svelte"

  let {
    children,
    class: className,
    ref = $bindable(null),
    ...rest
  }: Props = $props()
</script>

<dd bind:this={ref} class={["ui-description", className]} {...rest}>
  {@render children?.()}
</dd>
