// packages/opui/components/DescriptionList/Item.svelte
<script lang="ts">
  import type { ItemProps as Props } from "./types.svelte"

  const { children, class: className, ...rest }: Props = $props()

  let element = $state<HTMLDivElement | null>(null)
  export { element as this }
</script>

<div bind:this={element} class={["ui-item", className]} {...rest}>
  {@render children?.()}
</div>

// packages/opui/components/DescriptionList/Item.tsx
import { splitProps, type JSX } from "solid-js"
import { Dynamic } from "solid-js/web"
import type { Props } from "./types.solid"

export default function Item(props: Props) {
  const [local, rest] = splitProps(props, ["class", "as", "children"])
  
  return (
    <Dynamic component={local.as || "div"} class={`ui-item ${local.class || ""}`} {...rest}>
      {local.children}
    </Dynamic>
  )
}
