// packages/opui/components/DescriptionList/Term.tsx
import { splitProps, type JSX } from "solid-js"
import { Dynamic } from "solid-js/web"
import type { Props } from "./types.solid"

export default function Term(props: Props) {
  const [local, rest] = splitProps(props, ["class", "as", "children"])
  
  return (
    <Dynamic component={local.as || "div"} class={`ui-term ${local.class || ""}`} {...rest}>
      {local.children}
    </Dynamic>
  )
}

// packages/opui/components/DescriptionList/Term.svelte
<script lang="ts">
  import type { TermProps as Props } from "./types.svelte"

  const { children, class: className, ...rest }: Props = $props()

  let element = $state<HTMLElement | null>(null)
  export { element as this }
</script>

<dt bind:this={element} class={["ui-term", className]} {...rest}>
  {@render children?.()}
</dt>
