// packages/opui/components/Table/Body.tsx
import { splitProps, type JSX } from "solid-js"
import { Dynamic } from "solid-js/web"
import type { Props } from "./types.solid"

export default function Body(props: Props) {
  const [local, rest] = splitProps(props, ["class", "as", "children"])
  
  return (
    <Dynamic component={local.as || "div"} class={`ui-body ${local.class || ""}`} {...rest}>
      {local.children}
    </Dynamic>
  )
}

// packages/opui/components/Table/Body.svelte
<script lang="ts">
  import type { SectionProps as Props } from "./types.svelte"

  export const title = "Table Body" as const

  const { children, ...rest }: Props<"tbody"> = $props()

  let element = $state<HTMLTableSectionElement | null>(null)
  export { element as this }
</script>

<tbody bind:this={element} {...rest}>
  {@render children?.()}
</tbody>
