// packages/opui/components/Table/Cell.svelte
<script lang="ts">
  import type { SectionProps as Props } from "./types.svelte"

  export const title = "Table Cell" as const

  const { children, ...rest }: Props<"td"> = $props()

  let element = $state<HTMLTableCellElement | null>(null)
  export { element as this }
</script>

<td bind:this={element} {...rest}>
  {@render children?.()}
</td>

// packages/opui/components/Table/Cell.tsx
import { splitProps, type JSX } from "solid-js"
import { Dynamic } from "solid-js/web"
import type { Props } from "./types.solid"

export default function Cell(props: Props) {
  const [local, rest] = splitProps(props, ["class", "as", "children"])
  
  return (
    <Dynamic component={local.as || "div"} class={`ui-cell ${local.class || ""}`} {...rest}>
      {local.children}
    </Dynamic>
  )
}
