// packages/opui/components/Table/Column.vue
<script setup lang="ts">
import type { ColumnProps } from './types'

const { width } = defineProps<ColumnProps>()

defineOptions({
  inheritAttrs: false,
})

const colStyle = width
  ? width.includes(':')
    ? width
    : `width: ${width}`
  : undefined
</script>

<template>
  <col :style="colStyle" v-bind="$attrs" />
</template>

// packages/opui/components/Table/Column.tsx
import { omit } from "solid-js"
import type { ColumnProps } from "./types.solid"

export default function TableColumn(props: ColumnProps) {
  const rest = omit(props, "width")

  const colStyle = () =>
    props.width
      ? props.width.includes(":")
        ? props.width
        : `width: ${props.width}`
      : undefined

  return <col style={colStyle()} {...rest} />
}
