// packages/opui/components/Table/Head.svelte
<script lang="ts">
  import type { SectionProps as Props } from "./types.svelte"

  export const title = "Table Head" as const

  const { children, ...rest }: Props<"thead"> = $props()

  let element = $state<HTMLTableSectionElement | null>(null)
  export { element as this }
</script>

<thead bind:this={element} {...rest}>
  {@render children?.()}
</thead>

// packages/opui/components/Table/Head.tsx
import { splitProps, type JSX } from "solid-js"
import { Dynamic } from "solid-js/web"
import type { Props } from "./types.solid"

export default function Head(props: Props) {
  const [local, rest] = splitProps(props, ["class", "as", "children"])
  
  return (
    <Dynamic component={local.as || "div"} class={`ui-head ${local.class || ""}`} {...rest}>
      {local.children}
    </Dynamic>
  )
}
