// packages/opui/components/Table/Row.svelte
<script lang="ts">
  import type { SectionProps as Props } from "./types.svelte"

  export const title = "Table Row" as const

  const { children, ...rest }: Props<"tr"> = $props()

  let element = $state<HTMLTableRowElement | null>(null)
  export { element as this }
</script>

<tr bind:this={element} {...rest}>
  {@render children?.()}
</tr>

// packages/opui/components/Table/Row.tsx
import { splitProps, type JSX } from "solid-js"
import { Dynamic } from "solid-js/web"
import type { Props } from "./types.solid"

export default function Row(props: Props) {
  const [local, rest] = splitProps(props, ["class", "as", "children"])
  
  return (
    <Dynamic component={local.as || "div"} class={`ui-row ${local.class || ""}`} {...rest}>
      {local.children}
    </Dynamic>
  )
}
