// packages/opui/components/Table/Table.vue
<script setup lang="ts">
import type { Props, Slots } from "./types.d.vue"

const { stickyHeader, variant } = defineProps<Props>()
defineSlots<Slots>()

defineOptions({
  inheritAttrs: false,
})
</script>

<template>
  <table
    :class="[
      'ui-table',
      { 'ui-sticky-header': stickyHeader },
      variant && `ui-${variant}`,
      $props.class,
    ]"
    v-bind="$attrs"
  >
    <slot></slot>
  </table>
</template>

// packages/opui/components/Table/Table.svelte
<script lang="ts">
  import type { Props } from "./types.svelte"

  let {
    children,
    class: className,
    stickyHeader,
    variant,
    ...rest
  }: Props = $props()
</script>

<table
  class={[
    "ui-table",
    { "ui-sticky-header": stickyHeader },
    variant && `ui-${variant}`,
    className,
  ]}
  {...rest}
>
  {@render children?.()}
</table>
